
/**
 * types.ts
 * ─────────
 * Central type definitions for the entire app.
 * Any interface shared between components should live here.
 */

// ─── QUIZ TYPES ──────────────────────────────────────────────────────────────

/**
 * A single multiple-choice question embedded directly inside a lesson.
 * All text is stored as translation keys resolved by `useLanguage().t()`.
 * Used by QuizLessonScreen — rendered when lesson.questions is defined.
 */
export interface EmbeddedQuizQuestion {
  /** Translation key for the question text (e.g. 'py_q1_q1'). */
  questionKey: string;
  /** Four translation keys for options A, B, C, D (in order). */
  optionKeys: [string, string, string, string];
  /** Index of the correct answer: 0=A, 1=B, 2=C, 3=D. */
  correctIndex: 0 | 1 | 2 | 3;
  /** Translation key for the explanation shown after the student answers. */
  feedbackKey: string;
}

// ─── LESSON ──────────────────────────────────────────────────────────────────

/**
 * A single lesson or challenge node on the roadmap.
 *
 * Rendering logic:
 *  - If `questions` is defined → QuizLessonScreen (read + multiple-choice quiz).
 *  - Otherwise               → LessonScreen (code editor + terminal output).
 */
export interface Lesson {
  /** Unique numeric ID used for progress tracking (completedLessons[pathId]). */
  id: number;
  /** Visual level number shown on the roadmap node. */
  level: number;
  /** Translation key for the lesson title (e.g. 'python_loops'). */
  titleKey: string;
  /** Internal icon name used by the LessonNode component (e.g. 'brain', 'star'). */
  icon: string;
  /** XP awarded to the student on completing this lesson. */
  xp: number;
  /** Accent color for this lesson's roadmap node (any CSS color string). */
  color: string;
  /** Lesson category — affects styling and sorting. */
  type: 'lesson' | 'quiz' | 'project';
  /** Visual variant of the roadmap node bubble. */
  nodeType: 'standard' | 'quiz' | 'project' | 'trophy' | 'game';
  /** Translation key for the main challenge/task description. */
  challengeDescriptionKey: string;
  /** Translation key for the concept explanation shown in the theory card. */
  explanationKey?: string;
  /** Pre-filled code shown in the editor when the lesson opens. */
  starterCode: string;
  /** The exact code that produces the expected output (used internally). */
  solutionCode: string;
  /** The exact string the student's code must output to pass the lesson. */
  expectedOutput: string;
  /** Translation key for the contextual hint text shown on request. */
  hintKey?: string;
  /** Estimated time in minutes — shown as a badge in the lesson header. */
  estimatedMinutes?: number;
  /** Difficulty label shown as a colored badge. */
  difficulty?: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  /** Short topic tags shown as pills (e.g. ['Variables', 'DataTypes']). */
  tags?: string[];
  /** Translation key for |-separated learning objectives (e.g. 'py_obj_1'). */
  objectivesKey?: string;
  /** Translation key for the expert pro-tip shown at the bottom of the theory. */
  proTipKey?: string;
  /**
   * Quiz questions for this lesson.
   * When present, App.tsx renders QuizLessonScreen instead of LessonScreen.
   */
  questions?: EmbeddedQuizQuestion[];
}

// ─── AI QUIZ (used by TeacherDashboard / Creations) ─────────────────────────

/**
 * A quiz question generated by the AI teacher feature.
 * Different from EmbeddedQuizQuestion — stores raw text, not translation keys.
 */
export interface QuizQuestion {
  id: number;
  question: string;
  type?: 'multiple-choice' | 'true-false' | 'fill-in-the-blank' | 'matching';
  options: string[];
  answer: string;
  explanation: string;
  pairs?: { left: string, right: string }[];
}

export interface Creation {
  id: string;
  title: string;
  date: string;
  contentType: 'quiz' | 'game' | 'book';
  stageKey: string;
  questionCount: number;
  language: string;
  data: QuizQuestion[];
}

export interface LessonSection {
  id: string;
  titleKey: string;
  lessons: Lesson[];
}

export interface Module {
  id: string;
  titleKey: string;
  descriptionKey: string;
  color: string;
  levels: Level[];
}

export interface Level {
  id: string;
  titleKey: string;
  lessons: Lesson[];
  isLocked: boolean;
}

export interface UserProgress {
  xp: number;
  streak: number;
  completedLessons: {
    [pathId: string]: number[]; // e.g., { block_coding: [1, 2], python: [1] }
  };
  scores: {
    [lessonId: number]: number; // e.g., { 3: 100, 5: 85 }
  };
  badgesEarned: {
    [pathId: string]: string[]; // e.g., { block_coding: ['bc_badge1'], python: ['py_badge1'] }
  };
  lastLessonCompletedDate: string | null;
  lastLeaderboardRank?: number;
  skillMastery?: {
    [concept: string]: number;
  };
  learningProfile?: {
    strengths: string[];
    weaknesses: string[];
    recommendation: string;
    lastUpdated: string;
  };
  skillGraph?: {
    nodes?: Array<{ id: string; label: string; status: 'locked' | 'available' | 'mastered' }>;
    edges?: Array<{ from: string; to: string }>;
    unlockedAvatarItems?: number[];
    equippedAvatarItems?: number[];
    dailyQuestsDate?: string;
    chestOpenedToday?: boolean;
    dailyQuests?: Array<{
      id: string;
      type: 'lesson' | 'xp' | 'quiz';
      targetValue: number;
      currentValue: number;
      titleKey: string;
      xpReward: number;
    }>;
  };
}

export enum Language {
  EN = 'en',
  FR = 'fr',
  AR = 'ar',
}

export interface Badge {
  id: string;
  icon: string;
  titleKey: string;
  lessonId: number; // The ID of the lesson that unlocks this badge within its path
}

export type ProgrammingPath = {
  id: 'block_coding' | 'python' | 'javascript' | 'lua' | 'web_dev' | 'c++' | 'c_sharp' | 'java' | 'kotlin' | 'swift' | 'go' | 'rust' | 'php' | 'ruby' | 'typescript' | 'sql' | 'r' | 'dart' | 'scala' | 'math';
  titleKey: string;
  descriptionKey: string;
  icon: string;
  color: string;
  isAvailable: boolean;
};

export interface User {
  _id: string; // Changed from 'id' to match MongoDB's default identifier
  name: string;
  email: string;
  profilePictureUrl: string;
  bio?: string;
  coverPictureUrl?: string;
  password?: string; // Optional for OAuth users
  provider: 'google' | 'email';
  role: 'teacher' | 'student' | 'admin';
  classroomCode?: string; // Optional code provided by teacher for class enrollment
  progress: UserProgress;
  currentPath: ProgrammingPath['id'] | null;
  savedRepos?: string[];
  savedPosts?: string[];
  createdAt: string;
  lastLogin: string;
  githubUrl?: string;
  linkedinUrl?: string;
  websiteUrl?: string;
  professionalTitle?: string;
  skills?: string[];
}

export interface DBCourse {
  _id: string;
  title: string;
  description?: string;
  lessons: string[]; // Lesson IDs
  owner: string; // User ID
  createdAt: string;
  updatedAt: string;
}

export interface DBLesson {
  _id: string;
  course: string; // Course ID
  title: string;
  description?: string;
  exercises: string[]; // Exercise IDs
  xp: number;
  createdAt: string;
  updatedAt: string;
}

export interface DBExercise {
  _id: string;
  lesson: string; // Lesson ID
  instruction: string;
  starterCode?: string;
  solutionCode?: string;
  expectedOutput?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DBSubmission {
  _id: string;
  user: string; // User ID
  exercise: string; // Exercise ID
  submittedCode: string;
  score?: number;
  status: 'passed' | 'failed' | 'pending';
  output?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppNotification {
  _id: string;
  userId: string;
  title: string;
  message: string;
  type: 'lesson_completed' | 'streak_at_risk' | 'leaderboard_rank_change' | 'course_unlocked' | 'general';
  read: boolean;
  createdAt: string;
}

