
import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import { Language } from '../types';

const translations = {
  en: {
    path: '/en',
    home: 'Home',
    learn: 'Learn Code',
    profile: 'Profile',
    creations: 'Creations',
    shop: 'Shop',
    xp: 'XP',
    streak: 'Streak',
    start: 'Start',
    locked: 'Locked',
    completed: 'Completed',
    lesson_complete: 'Lesson Complete!',
    you_earned: 'You earned',
    continue: 'Continue',
    exit: 'Exit',
    login: 'Login',
    signUp: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    create_account: 'Create Account',
    or_continue_with: 'OR',
    continue_with_google: 'Continue with Google',
    logout: 'Logout',
    welcome_back: 'Welcome Back!',
    join_the_adventure: 'Join the Adventure!',
    my_profile: 'My Profile',
    my_badges: 'My Badges',
    my_creations: 'My Creations',
    start_creating_prompt: 'Create your first game to see it here!',
    skip_for_now: 'Skip for now',
    choose_your_path: 'Choose Your Path!',
    coming_soon: 'Coming Soon',
    change_path: 'Change Path',
    back: 'Back',
    next: 'Next',
    search_lessons: 'Search lessons...',
    goals: 'Goals',
    leaderboard: 'Leaderboard',
    store: 'Store',
    settings: 'Settings',
    settings_language_desc: 'Choose the language for the application interface.',
    appearance: 'Appearance',
    light_mode: 'Light Mode',
    dark_mode: 'Dark Mode',
    stepper_learning_outcomes: 'Learning Outcomes',
    upload_file_or_select_source: 'Upload File or Select Source',
    drag_drop_file: 'Drag & drop a file here',
    choose_a_file: 'Choose a file',
    supported_file_types: 'Supported types: PDF, DOCX, TXT',
    uploaded_files: 'Uploaded Files',
    total_file_size: 'Total Size',
    content_language: 'Content Language',
    ai_creating_quiz: 'AI is creating your quiz...',
    ai_warning: 'This may take a few seconds.',
    stepper_preview: 'Preview',
    challenge: 'Challenge',
    run_code: 'Run Code',
    language_english: 'English',
    language_french: 'French',
    language_arabic: 'Arabic',
    speaking_wizard_duration_title: 'Conversation Duration',
    appearance_desc: 'Switch between light and dark mode to keep your eyes happy!',
    wip: '(WIP)',
    // Home Hub
    welcome_message: 'Ready for your next coding adventure?',
    magic_found: "I've found some magic for you! 🪄",
    day_streak: 'Day Streak',
    total_xp_label: 'Total XP',
    learn_adventure_desc: 'Unlock new worlds and master magic code spells!',
    create_adventure_desc: 'Use your powers to build games and stories!',
    did_you_know: 'Did you know?',
    code_fact: 'Code is just a list of instructions for your robot friend!',
    // Quiz Play
    perfect_score: 'Perfect!',
    well_done: 'Well Done!',
    mission_accomplished: 'Mission Accomplished',
    questions_correct: 'Questions Correct',
    return_to_hub: 'Return to Hub',
    choose_magic_spell: 'Choose the right magic spell!',
    check_answer: 'Check Answer',
    amazing_feedback: 'Amazing!',
    correct_answer_label: 'Correct answer:',
    keep_up_magic: 'Keep up the magic!',
    // Lesson Screen
    genius: 'GENIUS!',
    mission_complete_msg: 'You completed the mission!',
    star_xp_units: 'STAR XP',
    next_adventure: 'Next Adventure!',
    code_editor_title: 'Code Editor',
    running: 'Running...',
    solution: 'Solution',
    use_this_code: 'Use this code',
    im_a_teacher: "I'm a teacher",
    im_a_student: "I'm a student",
    // Wizard
    last_details: 'Last Details',
    questions_label: 'Questions',
    generate_magic: 'GENERATE WITH MAGIC',
    save_creation: 'SAVE CREATION',
    consulting_ai: 'Consulting the AI Teachers...',
    back_button: 'BACK',
    continue_button: 'CONTINUE',
    // Creations
    no_content_saved: 'No content saved yet.',
    vault_empty: 'Your magic vault is empty.',
    start_creating_now: 'Create something in the Game Studio to get started!',
    view_all: 'View All',
    recent_contents: 'Recent Contents',
    content_type: 'Content Type',
    stage: 'Stage',
    question_count: 'Question Count',
    language_label: 'Language',
    view_learning_outcomes: 'View Learning Outcomes',
    assign: 'Assign',
    open_content: 'Open',
    rename: 'Rename',
    share: 'Share',
    quiz: 'Quiz',
    multiple_choice: 'Multiple-choice',
    // Profile
    following: 'Following',
    followers: 'Followers',
    league_label: 'League',
    no_bio: 'No bio yet. Ready for adventure!',
    unlocked_status: 'UNLOCKED',
    locked_status: 'LOCKED',
    edit_profile: 'Edit Profile',
    cancel: 'Cancel',
    save: 'Save',
    name_label: 'Name',
    bio_label: 'Bio',
    // Others
    type_or_talk: 'Type or talk...',
    time_left: 'Time left',
    // Curriculum
    curriculum_moroccan: 'Moroccan National Curriculum',
    curriculum_ib: 'International Baccalaureate (IB)',
    curriculum_us_core: 'U.S. Core Standards',
    stage_preschool: 'Preschool (4-5 yrs)',
    stage_primary: 'Primary Education (6 yrs)',
    stage_lower_secondary: 'Lower Secondary (3 yrs)',
    stage_upper_secondary: 'Upper Secondary (3 yrs)',
    select_curriculum: 'Select Curriculum',
    select_stage: 'Select Stage',
    stage_1: 'Stage 1',
    stage_2: 'Stage 2',
    stage_3: 'Stage 3',
    stage_4: 'Stage 4',
    stage_5: 'Stage 5',
    stage_6: 'Stage 6',
    // Game Studio Screen
    game_studio: 'Game Studio',
    game_studio_desc: 'Create interactive whiteboard games or assignments on any subject with AI.',
    create: 'Create',
    game_studio_import_title: 'Import Your Content',
    game_studio_import_desc: 'Easily create your games or assignments with AI using any material.',
    game_studio_math_title: 'Math',
    game_studio_math_desc: 'Easily create your maths games or assignments according to the curriculum and specific learning outcomes with AI.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Easily create your science games or assignments according to the curriculum and specific learning outcomes with AI.',
    game_studio_french_title: 'French',
    game_studio_french_desc: 'Easily create your French language games or assignments according to the curriculum and specific learning outcomes with AI.',
    // Question Lab Screen
    question_lab: 'Question Lab',
    question_lab_desc: 'Generate quizzes, multiple-choice or open-ended questions for activities with AI.',
    generate: 'Generate',
    question_lab_import_desc: 'Easily create practice questions, quizzes, tests, or assignments with AI using any material.',
    question_lab_math_desc: 'Easily create math questions, quizzes, tests, or assignments according to the curriculum with AI.',
    question_lab_science_desc: 'Easily create your science questions, quizzes, tests, or assignments according to the curriculum with AI.',
    question_lab_french_desc: 'Easily create your French language questions, quizzes, tests, or assignments according to the curriculum with AI.',
    // Smart Books
    smart_books: 'Smart Books',
    smart_books_desc: 'Use AI to create your own book or access reading books in your language.',
    open: 'Open',
    // Speaking Hub
    speaking_hub: 'Speaking Hub',
    speaking_hub_desc: 'Practice speaking a foreign language and improve your skills with AI.',
    start_speaking: 'Start Speaking',
    speaking_wizard_level: 'Level',
    speaking_wizard_age: 'Age',
    speaking_wizard_subject: 'Subject',
    speaking_wizard_duration: 'Duration',
    speaking_wizard_duration_mins: 'mins',
    speaking_wizard_topic_title: 'Topic',
    // ... paths ...
    // Paths
    paths: 'Paths',
    block_coding: 'Block Coding',
    block_coding_desc: 'Start with fun, colorful blocks. Perfect for beginners!',
    sequences: 'Sequences',
    loops: 'Loops',
    events: 'Events',
    maze_game: 'Maze Game',
    logic: 'Logic',
    conditionals: 'Conditionals',
    variables: 'Variables',
    logic_master: 'Logic Master',
    python: 'Python',
    python_desc: 'Jump into real-world code with the Python language.',
    javascript: 'JavaScript',
    javascript_desc: 'Build cool websites and apps with the language of the web.',
    lua: 'Lua',
    lua_desc: 'Create powerful games and scripts with the Lua language.',
    web_dev: 'Web Dev',
    web_dev_desc: 'Build your very first websites with HTML and CSS.',
    python_data_structures: 'Data Structures',
    python_lists: 'Lists',
    python_dicts: 'Dictionaries',
    python_tuples: 'Tuples',
    js_async_title: 'Asynchronous JS',
    js_promises: 'Promises',
    js_async_await: 'Async/Await',
    js_fetch_api: 'Fetch API',
    web_advanced_title: 'Advanced Layouts',
    web_flexbox: 'Flexbox',
    web_grid: 'CSS Grid',
    web_responsive_design: 'Responsive Design',
    cpp_advanced_title: 'Advanced C++',
    cpp_templates: 'Templates',
    cpp_memory: 'Memory Management',
    cpp_quiz_adv: 'Advanced Quiz',
    java_advanced_title: 'Advanced Java',
    java_streams: 'Streams API',
    java_lambdas: 'Lambda Expressions',
    java_multithreading: 'Multithreading',
    sql_advanced_title: 'Advanced SQL',
    sql_subqueries: 'Subqueries',
    sql_transactions: 'Transactions',
    sql_indexing: 'Indexing',
    // Challenges
    py_challenge_1: 'Create a variable named "age" and set it to 10. Then print it!',
    py_challenge_2: 'Use a loop to print numbers 1, 2, and 3.',
    py_challenge_3: 'Quiz: How do you check if a number is even?',
    py_challenge_4: 'Create a function that says "Hello!".',
    py_challenge_5: 'Build a mini quiz game!',
    py_challenge_6: 'Create a list of fruits.',
    py_challenge_7: 'Create a user dictionary.',
    py_challenge_8: 'Quiz: What is the difference between a list and a tuple?',
    js_challenge_1: 'Print "Hello, JavaScript!" to the console.',
    js_challenge_2: 'Create a variable named "score" and print it.',
    js_challenge_3: 'Quiz: Which keyword is used for variables?',
    js_challenge_4: 'Create a function that says "Hi!".',
    js_challenge_5: 'Build an interactive story!',
    js_challenge_6: 'Create a simple Promise.',
    js_challenge_7: 'Use async/await to return a value.',
    js_challenge_8: 'Quiz: What does fetch() return?',
    web_challenge_1: 'Create your first HTML heading!',
    web_challenge_2: 'Add an image to your page.',
    web_challenge_3: 'Quiz: What does CSS stand for?',
    web_challenge_4: 'Use Flexbox to align items.',
    web_challenge_5: 'Build a page about your favorite animal!',
    web_challenge_6: 'Center items using Flexbox.',
    web_challenge_7: 'Create a 2-column grid.',
    web_challenge_8: 'Quiz: How do you make a site mobile-friendly?',
    bc_challenge_1: 'Move forward 3 times!',
    bc_challenge_2: 'Turn left and move forward.',
    bc_challenge_3: 'Navigate the path!',
    bc_challenge_4: 'Escape the maze!',
    bc_challenge_5: 'Quiz: What is a loop?',
    bc_challenge_6: 'Jump 5 times using a loop.',
    bc_challenge_7: 'Handle a click event.',
    bc_challenge_8: 'Quiz: What is an event?',
    bc_challenge_9: 'Use a condition to check a number.',
    bc_challenge_10: 'Store a value in a variable.',
    bc_challenge_11: 'Become a logic master!',
    bc_hint_1: 'Try writing console.log("forward") three times!',
    bc_hint_2: 'First log "left", then log "forward".',
    show_hint: 'Show Hint',
    hide_hint: 'Hide Hint',
    py_hint_1: 'Variables are like boxes. Use age = 10.',
    py_hint_2: 'Use range(1, 4) to get numbers 1, 2, and 3.',
    js_hint_1: 'Type console.log("Hello, JavaScript!"); exactly.',
    js_hint_2: 'Use let score = 100; to create your variable.',
    web_hint_1: 'Tags start with < and end with >. Try <h1>Hello World</h1>.',
    web_hint_2: 'Use single quotes for the string if the tag has double quotes: \'<img src="magic.png">\'.',
    cpp_challenge_1: 'Print "Hello C++!" to the console.',
    cpp_challenge_2: 'Use a pointer to access a variable.',
    cpp_challenge_3: 'Quiz: What is a class?',
    cpp_challenge_4: 'Use the STL vector.',
    cpp_challenge_5: 'Build a calculator!',
    java_challenge_1: 'Print "Hello Java" to the console.',
    java_challenge_2: 'Create your first Java class.',
    java_challenge_3: 'Quiz: What is an ArrayList?',
    java_challenge_4: 'Build a bank account system!',
    sql_challenge_1: 'Select all users from the database.',
    sql_challenge_2: 'Filter users by age.',
    sql_challenge_3: 'Quiz: What is a JOIN?',
    sql_challenge_4: 'Query a complex database!',
    ts_challenge_1: 'Define a variable with a specific type.',
    ts_challenge_2: 'Create an interface for a user.',
    ts_challenge_3: 'Quiz: What are Generics?',
    ts_challenge_4: 'Build a typed Todo list!',
    bc_mod_1_title: 'Foundations of Logic',
    bc_mod_1_desc: 'Master the basic building blocks of programming.',
    bc_lvl_1_title: 'Level 1: Sequences',
    bc_lvl_2_title: 'Level 2: Loops',
    bc_mod_2_title: 'Intermediate Concepts',
    bc_mod_2_desc: 'Take your coding skills to the next level with events and data.',
    bc_lvl_3_title: 'Level 3: Events',
  },
  fr: {
    path: '/fr',
    home: 'Accueil',
    learn: 'Apprendre',
    profile: 'Profil',
    creations: 'Créations',
    shop: 'Boutique',
    xp: 'XP',
    streak: 'Série',
    start: 'Commencer',
    locked: 'Verrouillé',
    completed: 'Terminé',
    lesson_complete: 'Leçon Terminée !',
    you_earned: 'Tu as gagné',
    continue: 'Continuer',
    exit: 'Quitter',
    login: 'Connexion',
    signUp: 'S\'inscrire',
    username: 'Nom d\'utilisateur',
    email: 'E-mail',
    password: 'Mot de passe',
    create_account: 'Créer un compte',
    or_continue_with: 'OU',
    continue_with_google: 'Continuer avec Google',
    logout: 'Déconnexion',
    welcome_back: 'Bon Retour !',
    join_the_adventure: 'Rejoins l\'aventure !',
    my_profile: 'Mon Profil',
    my_badges: 'Mes Badges',
    my_creations: 'Mes Créations',
    start_creating_prompt: 'Crée ton premier jeu pour le voir ici !',
    skip_for_now: 'Passer pour l\'instant',
    choose_your_path: 'Choisis Ton Aventure !',
    coming_soon: 'Bientôt Disponible',
    change_path: 'Changer de Voie',
    back: 'Retour',
    next: 'Suivant',
    search_lessons: 'Rechercher des leçons...',
    goals: 'Objectifs',
    leaderboard: 'Classement',
    store: 'Boutique',
    settings: 'Réglages',
    settings_language_desc: 'Choisissez la langue de l\'interface.',
    appearance: 'Apparence',
    light_mode: 'Mode Clair',
    dark_mode: 'Mode Sombre',
    stepper_learning_outcomes: 'Objectifs d\'apprentissage',
    upload_file_or_select_source: 'Télécharger un fichier ou sélectionner une source',
    drag_drop_file: 'Glissez-déposez un fichier ici',
    choose_a_file: 'Choisir un fichier',
    supported_file_types: 'Types supportés : PDF, DOCX, TXT',
    uploaded_files: 'Fichiers téléchargés',
    total_file_size: 'Taille totale',
    content_language: 'Langue du contenu',
    ai_creating_quiz: 'L\'IA crée votre quiz...',
    ai_warning: 'Cela peut prendre quelques secondes.',
    stepper_preview: 'Aperçu',
    challenge: 'Défi',
    run_code: 'Exécuter le code',
    language_english: 'Anglais',
    language_french: 'Français',
    language_arabic: 'Arabe',
    speaking_wizard_duration_title: 'Durée de la conversation',
    appearance_desc: 'Changez de mode pour le confort de vos yeux !',
    wip: '(En cours)',
    // Home Hub
    welcome_message: 'Prêt pour ta prochaine aventure ?',
    magic_found: "J'ai trouvé de la magie pour toi ! 🪄",
    day_streak: 'Série de Jours',
    total_xp_label: 'XP Total',
    learn_adventure_desc: 'Débloque de nouveaux mondes et maîtrise les sorts de code !',
    create_adventure_desc: 'Utilise tes pouvoirs pour construire des jeux !',
    did_you_know: 'Le savais-tu ?',
    code_fact: 'Le code est juste une liste d\'instructions pour ton ami robot !',
    // Quiz Play
    perfect_score: 'Parfait !',
    well_done: 'Bien joué !',
    mission_accomplished: 'Mission Accomplie',
    questions_correct: 'Questions Correctes',
    return_to_hub: 'Retour à l\'Accueil',
    choose_magic_spell: 'Choisis le bon sort magique !',
    check_answer: 'Vérifier',
    amazing_feedback: 'Incroyable !',
    correct_answer_label: 'Bonne réponse :',
    keep_up_magic: 'Continue comme ça !',
    // Lesson Screen
    genius: 'GÉNIE !',
    mission_complete_msg: 'Tu as terminé la mission !',
    star_xp_units: 'XP ÉTOILE',
    next_adventure: 'Prochaine Aventure !',
    code_editor_title: 'Éditeur de Code',
    running: 'Exécution...',
    solution: 'Solution',
    use_this_code: 'Utiliser ce code',
    im_a_teacher: "Je suis un enseignant",
    im_a_student: "Je suis un étudiant",
    // Wizard
    last_details: 'Derniers Détails',
    questions_label: 'Questions',
    generate_magic: 'GÉNÉRER AVEC MAGIE',
    save_creation: 'SAUVEGARDER',
    consulting_ai: 'Consultation des Professeurs IA...',
    back_button: 'RETOUR',
    continue_button: 'CONTINUER',
    // Creations
    no_content_saved: 'Aucun contenu enregistré.',
    vault_empty: 'Ton coffre magique est vide.',
    start_creating_now: 'Crée quelque chose dans le Studio pour commencer !',
    view_all: 'Voir Tout',
    recent_contents: 'Contenus Récents',
    content_type: 'Type de Contenu',
    stage: 'Niveau',
    question_count: 'Nombre de Questions',
    language_label: 'Langue',
    view_learning_outcomes: 'Voir les Objectifs',
    assign: 'Assigner',
    open_content: 'Ouvrir',
    rename: 'Renommer',
    share: 'Partager',
    quiz: 'Quiz',
    multiple_choice: 'Choix multiple',
    // Profile
    following: 'Abonnements',
    followers: 'Abonnés',
    league_label: 'Ligue',
    no_bio: 'Pas encore de bio. Prêt pour l\'aventure !',
    unlocked_status: 'DÉBLOQUÉ',
    locked_status: 'VERROUILLÉ',
    edit_profile: 'Modifier le Profil',
    cancel: 'Annuler',
    save: 'Enregistrer',
    name_label: 'Nom',
    bio_label: 'Bio',
    // Others
    type_or_talk: 'Écris ou parle...',
    time_left: 'Temps restant',
    // Curriculum
    curriculum_moroccan: 'Programme National Marocain',
    curriculum_ib: 'Baccalauréat International (IB)',
    curriculum_us_core: 'Normes US Core',
    stage_preschool: 'Préscolaire (4-5 ans)',
    stage_primary: 'Primaire (6 ans)',
    stage_lower_secondary: 'Collège (3 ans)',
    stage_upper_secondary: 'Lycée (3 ans)',
    select_curriculum: 'Sélectionner le Programme',
    select_stage: 'Sélectionner le Niveau',
    stage_1: 'Niveau 1',
    stage_2: 'Niveau 2',
    stage_3: 'Niveau 3',
    stage_4: 'Niveau 4',
    stage_5: 'Niveau 5',
    stage_6: 'Niveau 6',
    // Game Studio
    game_studio: 'Studio de Jeux',
    game_studio_desc: 'Créez des jeux interactifs ou des devoirs avec l\'IA.',
    create: 'Créer',
    game_studio_import_title: 'Importer Votre Contenu',
    game_studio_import_desc: 'Créez facilement vos jeux avec l\'IA en utilisant n\'importe quel matériel.',
    game_studio_math_title: 'Maths',
    game_studio_math_desc: 'Jeux de maths conformes au programme avec l\'IA.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Jeux de science conformes au programme avec l\'IA.',
    game_studio_french_title: 'Français',
    game_studio_french_desc: 'Jeux de français conformes au programme avec l\'IA.',
    // Question Lab
    question_lab: 'Labo Questions',
    question_lab_desc: 'Générez des quiz et des devoirs avec l\'IA.',
    generate: 'Générer',
    question_lab_import_desc: 'Créez des questions d\'entraînement avec l\'IA.',
    question_lab_math_desc: 'Questions de maths conformes au programme.',
    question_lab_science_desc: 'Questions de sciences conformes au programme.',
    question_lab_french_desc: 'Questions de français conformes au programme.',
    // Smart Books
    smart_books: 'Livres Intelligents',
    smart_books_desc: 'Utilisez l\'IA pour créer votre livre ou lire dans votre langue.',
    open: 'Ouvrir',
    // Speaking Hub
    speaking_hub: 'Hub de Parole',
    speaking_hub_desc: 'Entraînez-vous à parler une langue étrangère avec l\'IA.',
    start_speaking: 'Commencer',
    speaking_wizard_level: 'Niveau',
    speaking_wizard_age: 'Âge',
    speaking_wizard_subject: 'Sujet',
    speaking_wizard_duration: 'Durée',
    speaking_wizard_duration_mins: 'min',
    speaking_wizard_topic_title: 'Sujet',
    // ... paths ...
    // Paths
    paths: 'Parcours',
    block_coding: 'Code en Blocs',
    block_coding_desc: 'Commencez avec des blocs colorés !',
    sequences: 'Séquences',
    loops: 'Boucles',
    events: 'Événements',
    maze_game: 'Labyrinthe',
    logic: 'Logique',
    conditionals: 'Conditions',
    variables: 'Variables',
    logic_master: 'Maître de la Logique',
    python: 'Python',
    python_desc: 'Plongez dans le code avec Python.',
    javascript: 'JavaScript',
    javascript_desc: 'Créez des sites avec le langage du web.',
    lua: 'Lua',
    lua_desc: 'Créez des jeux puissants avec Lua.',
    web_dev: 'Web Dev',
    web_dev_desc: 'Construisez vos sites avec HTML et CSS.',
    python_data_structures: 'Structures de Données',
    python_lists: 'Listes',
    python_dicts: 'Dictionnaires',
    python_tuples: 'Tuples',
    js_async_title: 'JS Asynchrone',
    js_promises: 'Promesses',
    js_async_await: 'Async/Await',
    js_fetch_api: 'API Fetch',
    web_advanced_title: 'Mises en Page Avancées',
    web_flexbox: 'Flexbox',
    web_grid: 'Grille CSS',
    web_responsive_design: 'Design Responsif',
    cpp_advanced_title: 'C++ Avancé',
    cpp_templates: 'Templates',
    cpp_memory: 'Gestion de la Mémoire',
    cpp_quiz_adv: 'Quiz Avancé',
    java_advanced_title: 'Java Avancé',
    java_streams: 'API Streams',
    java_lambdas: 'Expressions Lambda',
    java_multithreading: 'Multithreading',
    sql_advanced_title: 'SQL Avancé',
    sql_subqueries: 'Sous-requêtes',
    sql_transactions: 'Transactions',
    sql_indexing: 'Indexation',
    // Challenges
    py_challenge_1: 'Créez une variable nommée "age" et réglez-la sur 10. Puis affichez-la !',
    py_challenge_2: 'Utilisez une boucle pour afficher les nombres 1, 2 et 3.',
    py_challenge_3: 'Quiz : Comment vérifier si un nombre est pair ?',
    py_challenge_4: 'Créez une fonction qui dit "Bonjour !".',
    py_challenge_5: 'Construisez un mini jeu de quiz !',
    py_challenge_6: 'Créez une liste de fruits.',
    py_challenge_7: 'Créez un dictionnaire utilisateur.',
    py_challenge_8: 'Quiz : Quelle est la différence entre une liste et un tuple ?',
    js_challenge_1: 'Affichez "Hello, JavaScript!" dans la console.',
    js_challenge_2: 'Créez une variable nommée "score" et affichez-la.',
    js_challenge_3: 'Quiz : Quel mot-clé est utilisé pour les variables ?',
    js_challenge_4: 'Créez une fonction qui dit "Salut !".',
    js_challenge_5: 'Construisez une histoire interactive !',
    js_challenge_6: 'Créez une Promise simple.',
    js_challenge_7: 'Utilisez async/await pour retourner une valeur.',
    js_challenge_8: 'Quiz : Que retourne fetch() ?',
    web_challenge_1: 'Créez votre premier titre HTML !',
    web_challenge_2: 'Ajoutez une image à votre page.',
    web_challenge_3: 'Quiz : Que signifie CSS ?',
    web_challenge_4: 'Utilisez Flexbox pour aligner les éléments.',
    web_challenge_5: 'Construisez une page sur votre animal préféré !',
    web_challenge_6: 'Centrez les éléments avec Flexbox.',
    web_challenge_7: 'Créez une grille à 2 colonnes.',
    web_challenge_8: 'Quiz : Comment rendre un site adapté aux mobiles ?',
    bc_challenge_1: 'Avancez 3 fois !',
    bc_challenge_2: 'Tournez à gauche et avancez.',
    bc_challenge_3: 'Naviguez sur le chemin !',
    bc_challenge_4: 'Échappez-vous du labyrinthe !',
    bc_challenge_5: 'Quiz : Qu\'est-ce qu\'une boucle ?',
    bc_challenge_6: 'Sautez 5 fois en utilisant une boucle.',
    bc_challenge_7: 'Gérez un événement de clic.',
    bc_challenge_8: 'Quiz : Qu\'est-ce qu\'un événement ?',
    bc_challenge_9: 'Utilisez une condition pour vérifier un nombre.',
    bc_challenge_10: 'Stockez une valeur dans une variable.',
    bc_challenge_11: 'Devenez un maître de la logique !',
    bc_hint_1: 'Essayez d\'écrire console.log("forward") trois fois !',
    bc_hint_2: 'Affichez d\'abord "left", puis "forward".',
    show_hint: 'Afficher l\'indice',
    hide_hint: 'Masquer l\'indice',
    py_hint_1: 'Les variables sont comme des boîtes. Utilisez age = 10.',
    py_hint_2: 'Utilisez range(1, 4) pour obtenir les nombres 1, 2 et 3.',
    js_hint_1: 'Tapez console.log("Hello, JavaScript!"); exactement.',
    js_hint_2: 'Utilisez let score = 100; pour créer votre variable.',
    web_hint_1: 'Les balises commencent par < et se terminent par >. Essayez <h1>Hello World</h1>.',
    web_hint_2: 'Utilisez des guillemets simples pour la chaîne si la balise a des guillemets doubles : \'<img src="magic.png">\'.',
    cpp_challenge_1: 'Affichez "Hello C++!" dans la console.',
    cpp_challenge_2: 'Utilisez un pointeur pour accéder à une variable.',
    cpp_challenge_3: 'Quiz : Qu\'est-ce qu\'une classe ?',
    cpp_challenge_4: 'Utilisez le vecteur STL.',
    cpp_challenge_5: 'Construisez une calculatrice !',
    java_challenge_1: 'Affichez "Hello Java" dans la console.',
    java_challenge_2: 'Créez votre première classe Java.',
    java_challenge_3: 'Quiz : Qu\'est-ce qu\'une ArrayList ?',
    java_challenge_4: 'Construisez un système de compte bancaire !',
    sql_challenge_1: 'Sélectionnez tous les utilisateurs de la base de données.',
    sql_challenge_2: 'Filtrez les utilisateurs par âge.',
    sql_challenge_3: 'Quiz : Qu\'est-ce qu\'une JOIN ?',
    sql_challenge_4: 'Interrogez une base de données complexe !',
    ts_challenge_1: 'Définissez une variable avec un type spécifique.',
    ts_challenge_2: 'Créez une interface pour un utilisateur.',
    ts_challenge_3: 'Quiz : Que sont les Generics ?',
    ts_challenge_4: 'Construisez une liste de tâches typée !',
    bc_mod_1_title: 'Bases de la Logique',
    bc_mod_1_desc: 'Maîtrisez les blocs de base de la programmation.',
    bc_lvl_1_title: 'Niveau 1 : Séquences',
    bc_lvl_2_title: 'Niveau 2 : Boucles',
    bc_mod_2_title: 'Concepts Intermédiaires',
    bc_mod_2_desc: 'Passez au niveau supérieur avec les événements et les données.',
    bc_lvl_3_title: 'Niveau 3 : Événements',
  },
  ar: {
    path: '/ar',
    home: 'الدار',
    learn: 'تعلم',
    profile: 'البروفيل',
    creations: 'داكشي اللي صاوبتي',
    shop: 'الحانوت',
    xp: 'نقطة',
    streak: 'السلسلة',
    start: 'بدا',
    locked: 'مسدود',
    completed: 'كملتي',
    lesson_complete: 'كملتي الدرس!',
    you_earned: 'ربحتي',
    continue: 'كمل',
    exit: 'خرج',
    login: 'دخل',
    signUp: 'صاوب حساب',
    username: 'سمية المستخدم',
    email: 'الإيميل',
    password: 'الكود',
    create_account: 'صاوب حساب',
    or_continue_with: 'ولا',
    continue_with_google: 'كمل بجوجل',
    logout: 'خرج',
    welcome_back: 'على سلامتك!',
    join_the_adventure: 'دخل للمغامرة!',
    my_profile: 'البروفيل ديالي',
    my_badges: 'الأوسمة ديالي',
    my_creations: 'داكشي اللي صاوبتي',
    start_creating_prompt: 'صاوب أول لعبة ديالك باش تبان هنا!',
    skip_for_now: 'دوز دابا',
    choose_your_path: 'ختار الطريق ديالك!',
    coming_soon: 'قريب',
    change_path: 'بدل الطريق',
    back: 'رجع',
    next: 'الجاي',
    search_lessons: 'قلب على الدروس...',
    goals: 'الأهداف',
    leaderboard: 'الترتيب',
    store: 'الحانوت',
    settings: 'الإعدادات',
    settings_language_desc: 'ختار اللغة ديال التطبيق.',
    appearance: 'الشكل',
    light_mode: 'الضو',
    dark_mode: 'الظلام',
    stepper_learning_outcomes: 'شنو غاتعلم',
    upload_file_or_select_source: 'طلع ملف ولا ختار منين',
    drag_drop_file: 'جر وحط الملف هنا',
    choose_a_file: 'ختار ملف',
    supported_file_types: 'الأنواع اللي خدامة: PDF, DOCX, TXT',
    uploaded_files: 'الملفات اللي طلعتي',
    total_file_size: 'الحجم كامل',
    content_language: 'اللغة ديال المحتوى',
    ai_creating_quiz: 'الذكاء الاصطناعي كيصاوب ليك الاختبار...',
    ai_warning: 'هادشي غاياخد شوية ديال الوقت.',
    stepper_preview: 'شوف قبل',
    challenge: 'تحدي',
    run_code: 'خدم الكود',
    language_english: 'الإنجليزية',
    language_french: 'الفرنسية',
    language_arabic: 'الدارجة',
    speaking_wizard_duration_title: 'شحال غاتهضر',
    appearance_desc: 'بدل بين الضو والظلام باش ترتاح عينيك!',
    wip: '(خدامين عليه)',
    // Home Hub
    welcome_message: 'واجد للمغامرة الجاية؟',
    magic_found: 'لقيت ليك شوية ديال السحر! 🪄',
    day_streak: 'السلسلة ديال الأيام',
    total_xp_label: 'مجموع النقط',
    learn_adventure_desc: 'حل عوالم جديدة وتعلم سحر الكود!',
    create_adventure_desc: 'استعمل القوة ديالك باش تصاوب ألعاب وقصص!',
    did_you_know: 'واش كتعرف؟',
    code_fact: 'الكود هو غير واحد الليستة ديال الأوامر للصديق ديالك الروبوت!',
    // Quiz Play
    perfect_score: 'واعر!',
    well_done: 'تبارك الله عليك!',
    mission_accomplished: 'المهمة كملات',
    questions_correct: 'أسئلة صحيحة',
    return_to_hub: 'رجع للدار',
    choose_magic_spell: 'ختار السحر الصحيح!',
    check_answer: 'شوف',
    amazing_feedback: 'خطير!',
    correct_answer_label: 'الجواب الصحيح:',
    keep_up_magic: 'كمل السحر ديالك!',
    // Lesson Screen
    genius: 'عبقري!',
    mission_complete_msg: 'كملتي المهمة!',
    star_xp_units: 'نقطة سحرية',
    next_adventure: 'المغامرة الجاية!',
    code_editor_title: 'بلاصة الكود',
    running: 'خدام...',
    solution: 'الحل',
    use_this_code: 'استعمل هاد الكود',
    im_a_teacher: "أنا أستاذ",
    im_a_student: "أنا تلميذ",
    // Wizard
    last_details: 'آخر التفاصيل',
    questions_label: 'أسئلة',
    generate_magic: 'صاوب بالسحر',
    save_creation: 'حفظ داكشي اللي صاوبتي',
    consulting_ai: 'كنسولو المعلمين ديال الذكاء الاصطناعي...',
    back_button: 'رجع',
    continue_button: 'كمل',
    // Creations
    no_content_saved: 'باقي ما حفظتي والو.',
    vault_empty: 'الخزنة السحرية ديالك خاوية.',
    start_creating_now: 'صاوب شي حاجة في ستوديو الألعاب باش تبدا!',
    view_all: 'شوف كلشي',
    recent_contents: 'آخر داكشي اللي صاوبتي',
    content_type: 'نوع المحتوى',
    stage: 'المرحلة',
    question_count: 'عدد الأسئلة',
    language_label: 'اللغة',
    view_learning_outcomes: 'شوف شنو غاتعلم',
    assign: 'عطي',
    open_content: 'حل',
    rename: 'بدل السمية',
    share: 'بارطاجي',
    quiz: 'اختبار',
    multiple_choice: 'متعدد الخيارات',
    // Profile
    following: 'متابعة',
    followers: 'متابعين',
    league_label: 'الدوري',
    no_bio: 'باقي ما كاين وصف. واجد للمغامرة!',
    unlocked_status: 'محلول',
    locked_status: 'مسدود',
    edit_profile: 'بدل البروفيل',
    cancel: 'حبس',
    save: 'حفظ',
    name_label: 'السمية',
    bio_label: 'الوصف',
    // Others
    type_or_talk: 'اكتب ولا هضر...',
    time_left: 'الوقت اللي بقى',
    // Curriculum
    curriculum_moroccan: 'المنهاج الوطني المغربي',
    curriculum_ib: 'البكالوريا الدولية (IB)',
    curriculum_us_core: 'المعايير الأمريكية',
    stage_preschool: 'التعليم الأولي (4-5 سنوات)',
    stage_primary: 'التعليم الابتدائي (6 سنوات)',
    stage_lower_secondary: 'التعليم الإعدادي (3 سنوات)',
    stage_upper_secondary: 'التعليم الثانوي (3 سنوات)',
    select_curriculum: 'ختار المنهاج',
    select_stage: 'ختار المرحلة',
    stage_1: 'المرحلة 1',
    stage_2: 'المرحلة 2',
    stage_3: 'المرحلة 3',
    stage_4: 'المرحلة 4',
    stage_5: 'المرحلة 5',
    stage_6: 'المرحلة 6',
    // Game Studio
    game_studio: 'ستوديو الألعاب',
    game_studio_desc: 'صاوب ألعاب تفاعلية ولا واجبات بالذكاء الاصطناعي.',
    create: 'صاوب',
    game_studio_import_title: 'جيب المحتوى ديالك',
    game_studio_import_desc: 'صاوب ألعابك بسهولة بأي حاجة عندك.',
    game_studio_math_title: 'رياضيات',
    game_studio_math_desc: 'ألعاب رياضيات على حساب المنهاج.',
    game_studio_science_title: 'علوم',
    game_studio_science_desc: 'ألعاب علوم على حساب المنهاج.',
    game_studio_french_title: 'فرنسية',
    game_studio_french_desc: 'ألعاب فرنسية على حساب المنهاج.',
    // Question Lab
    question_lab: 'مختبر الأسئلة',
    question_lab_desc: 'صاوب اختبارات وواجبات بالذكاء الاصطناعي.',
    generate: 'صاوب',
    question_lab_import_desc: 'صاوب أسئلة تدريبية بسهولة.',
    question_lab_math_desc: 'أسئلة رياضيات على حساب المنهاج.',
    question_lab_science_desc: 'أسئلة علوم على حساب المنهاج.',
    question_lab_french_desc: 'أسئلة فرنسية على حساب المنهاج.',
    // Smart Books
    smart_books: 'الكتب الذكية',
    smart_books_desc: 'استعمل الذكاء الاصطناعي باش تصاوب كتابك ولا تقرا باللغة ديالك.',
    open: 'حل',
    // Speaking Hub
    speaking_hub: 'مركز الهضرة',
    speaking_hub_desc: 'تدرب على الهضرة بلغة أجنبية مع الذكاء الاصطناعي.',
    start_speaking: 'بدا',
    speaking_wizard_level: 'المستوى',
    speaking_wizard_age: 'العمر',
    speaking_wizard_subject: 'الموضوع',
    speaking_wizard_duration: 'المدة',
    speaking_wizard_duration_mins: 'دقائق',
    speaking_wizard_topic_title: 'الموضوع',
    // ... paths ...
    // Paths
    paths: 'الطرق',
    block_coding: 'البرمجة بالبلوكات',
    block_coding_desc: 'بدا ببلوكات ملونة وزوينة!',
    sequences: 'التسلسلات',
    loops: 'الحلقات',
    events: 'الأحداث',
    maze_game: 'المتاهة',
    logic: 'المنطق',
    conditionals: 'الشروط',
    variables: 'المتغيرات',
    logic_master: 'سيد المنطق',
    python: 'بايثون',
    python_desc: 'تعلم البرمجة الحقيقية ببايثون.',
    javascript: 'جافاسكريبت',
    javascript_desc: 'صاوب مواقع الويب بجافاسكريبت.',
    lua: 'لوا',
    lua_desc: 'صاوب ألعاب قوية بلوا.',
    web_dev: 'تطوير الويب',
    web_dev_desc: 'صاوب مواقعك بـ HTML و CSS.',
    python_data_structures: 'هياكل البيانات',
    python_lists: 'الليستات',
    python_dicts: 'القواميس',
    python_tuples: 'الصفوف',
    js_async_title: 'جافاسكريبت غير المتزامنة',
    js_promises: 'الوعود',
    js_async_await: 'Async/Await',
    js_fetch_api: 'Fetch API',
    web_advanced_title: 'تخطيطات متقدمة',
    web_flexbox: 'Flexbox',
    web_grid: 'CSS Grid',
    web_responsive_design: 'التصميم المتجاوب',
    cpp_advanced_title: 'C++ متقدم',
    cpp_templates: 'القوالب',
    cpp_memory: 'إدارة الذاكرة',
    cpp_quiz_adv: 'اختبار متقدم',
    java_advanced_title: 'جافا متقدم',
    java_streams: 'Streams API',
    java_lambdas: 'تعبيرات لامبدا',
    java_multithreading: 'تعدد الخيوط',
    sql_advanced_title: 'SQL متقدم',
    sql_subqueries: 'الاستعلامات الفرعية',
    sql_transactions: 'المعاملات',
    sql_indexing: 'الفهرسة',
    // Challenges
    py_challenge_1: 'صاوب متغير سميتو "age" ودير فيه 10. ومن بعد طبعو!',
    py_challenge_2: 'استعمل حلقة باش تطبع الأرقام 1 و 2 و 3.',
    py_challenge_3: 'اختبار: كيفاش كتعرف واش الرقم زوجي؟',
    py_challenge_4: 'صاوب دالة كتقول "السلام!".',
    py_challenge_5: 'صاوب لعبة اختبار صغيرة!',
    py_challenge_6: 'صاوب ليستة ديال الفواكه.',
    py_challenge_7: 'صاوب قاموس ديال المستخدم.',
    py_challenge_8: 'اختبار: شنو الفرق بين الليستة والـ tuple؟',
    js_challenge_1: 'اطبع "Hello, JavaScript!" في الكونسول.',
    js_challenge_2: 'صاوب متغير سميتو "score" وطبعو.',
    js_challenge_3: 'اختبار: شنو هي الكلمة اللي كنستعملو للمتغيرات؟',
    js_challenge_4: 'صاوب دالة كتقول "السلام!".',
    js_challenge_5: 'صاوب قصة تفاعلية!',
    js_challenge_6: 'صاوب Promise بسيط.',
    js_challenge_7: 'استعمل async/await باش ترجع شي قيمة.',
    js_challenge_8: 'اختبار: شنو كترجع fetch()؟',
    web_challenge_1: 'صاوب أول عنوان HTML ديالك!',
    web_challenge_2: 'زيد تصويرة في الصفحة ديالك.',
    web_challenge_3: 'اختبار: شنو كتعني CSS؟',
    web_challenge_4: 'استعمل Flexbox باش تقاد العناصر.',
    web_challenge_5: 'صاوب صفحة على الحيوان المفضل ديالك!',
    web_challenge_6: 'وسط العناصر باستعمال Flexbox.',
    web_challenge_7: 'صاوب شبكة فيها 2 ديال الأعمدة.',
    web_challenge_8: 'اختبار: كيفاش كتخلي الموقع يخدم مزيان في التيليفون؟',
    bc_challenge_1: 'زيد القدام 3 ديال المرات!',
    bc_challenge_2: 'دور لليسر وزيد القدام.',
    bc_challenge_3: 'تمشى في الطريق!',
    bc_challenge_4: 'خرج من المتاهة!',
    bc_challenge_5: 'اختبار: شنو هي الحلقة (loop)؟',
    bc_challenge_6: 'نقز 5 ديال المرات باستعمال حلقة.',
    bc_challenge_7: 'خدم مع حدث النقر.',
    bc_challenge_8: 'اختبار: شنو هو الحدث (event)؟',
    bc_challenge_9: 'استعمل شرط باش تقلب شي رقم.',
    bc_challenge_10: 'خزن شي قيمة في متغير.',
    bc_challenge_11: 'ولي سيد المنطق!',
    bc_hint_1: 'جرب تكتب console.log("forward") تلاتة ديال المرات!',
    bc_hint_2: 'طبع "left" هي اللولة، ومن بعد "forward".',
    show_hint: 'وريني التلميح',
    hide_hint: 'خبي التلميح',
    py_hint_1: 'المتغيرات بحال الصنادق. استعمل age = 10.',
    py_hint_2: 'استعمل range(1, 4) باش تجيب الأرقام 1 و 2 و 3.',
    js_hint_1: 'اكتب console.log("Hello, JavaScript!"); كيفما هي.',
    js_hint_2: 'استعمل let score = 100; باش تصاوب المتغير ديالك.',
    web_hint_1: 'الوسوم كيبداو بـ < وكيساو بـ >. جرب <h1>Hello World</h1>.',
    web_hint_2: 'استعمل علامات الاقتباس المفردة للسلسلة إلا كان الوسم فيه علامات اقتباس مزدوجة: \'<img src="magic.png">\'.',
    cpp_challenge_1: 'طبع "Hello C++!" في الكونسول.',
    cpp_challenge_2: 'استعمل مؤشر (pointer) باش توصل لشي متغير.',
    cpp_challenge_3: 'اختبار: شنو هي الفئة (class)؟',
    cpp_challenge_4: 'استعمل STL vector.',
    cpp_challenge_5: 'صاوب مكينة حسابية!',
    java_challenge_1: 'طبع "Hello Java" في الكونسول.',
    java_challenge_2: 'صاوب أول فئة (class) جافا ديالك.',
    java_challenge_3: 'اختبار: شنو هي الـ ArrayList؟',
    java_challenge_4: 'صاوب نظام حساب بنكي!',
    sql_challenge_1: 'ختار كاع المستخدمين من قاعدة البيانات.',
    sql_challenge_2: 'عزل المستخدمين على حساب العمر.',
    sql_challenge_3: 'اختبار: شنو هو الـ JOIN؟',
    sql_challenge_4: 'قلب في قاعدة بيانات معقدة!',
    ts_challenge_1: 'عرف شي متغير بنوع محدد.',
    ts_challenge_2: 'صاوب واجهة (interface) للمستخدم.',
    ts_challenge_3: 'اختبار: شنو هي الـ Generics؟',
    ts_challenge_4: 'صاوب ليستة ديال المهام محددة الأنواع!',
    bc_mod_1_title: 'أساسيات المنطق',
    bc_mod_1_desc: 'تعلم البلوكات الأساسية ديال البرمجة.',
    bc_lvl_1_title: 'المستوى 1: التسلسلات',
    bc_lvl_2_title: 'المستوى 2: الحلقات',
    bc_mod_2_title: 'مفاهيم متوسطة',
    bc_mod_2_desc: 'زيد القدام في البرمجة مع الأحداث والبيانات.',
    bc_lvl_3_title: 'المستوى 3: الأحداث',
  },
};

type TranslationKey = keyof (typeof translations)['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(Language.EN);

  useEffect(() => {
    const dir = language === Language.AR ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language]);

  const t = (key: TranslationKey) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
