
import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import { Language } from '../types';

const translations = {
  en: {
    learn: 'Learn',
    profile: 'Profile',
    creations: 'Creations',
    shop: 'Shop',
    xp: 'XP',
    streak: 'Streak',
    start: 'Start',
    locked: 'Locked',
    completed: 'Completed',
    lesson_complete: 'Lesson Complete!',
    you_earned: 'You earned',
    continue: 'Continue',
    exit: 'Exit',
    login: 'Login',
    signUp: 'Sign Up',
    username: 'Username',
    password: 'Password',
    create_account: 'Create Account',
    logout: 'Logout',
    welcome_back: 'Welcome Back!',
    join_the_adventure: 'Join the Adventure!',
    my_profile: 'My Profile',
    my_badges: 'My Badges',
    my_creations: 'My Creations',
    start_creating_prompt: 'Create your first game to see it here!',
    skip_for_now: 'Skip for now',
    choose_your_path: 'Choose Your Path!',
    coming_soon: 'Coming Soon',
    change_path: 'Change Path',
    back: 'Back',
    next: 'Next',
    // Creation Screen
    game_studio: 'Game Studio',
    game_studio_desc: 'Create interactive whiteboard games or assignments on any subject with AI.',
    create: 'Create',
    question_lab: 'Question Lab',
    question_lab_desc: 'Generate quizzes, multiple-choice or open-ended questions for in-class activities, homework, or printable materials with AI.',
    generate: 'Generate',
    smart_books: 'Smart Books',
    smart_books_desc: 'Use AI to create your own book or access reading books in your own language or foreign languages.',
    open: 'Open',
    scientific_inquiry: 'Scientific Inquiry',
    scientific_inquiry_desc: 'Ask your friendly AI companion any question you like and get an instant answer.',
    speaking_hub: 'Speaking Hub',
    speaking_hub_desc: 'Use a voice-based AI model to practice speaking a foreign language and improve your language skills.',
    start_speaking: 'Start Speaking',
    recent_contents: 'Recent Contents',
    view_all: 'View All',
    content_type: 'Content Type',
    stage: 'Stage',
    question_count: 'Question Count',
    language_label: 'Language',
    view_learning_outcomes: 'View Learning Outcomes',
    assign: 'Assign',
    open_content: 'Open',
    rename: 'Rename',
    share: 'Share',
    quiz: 'Quiz',
    multiple_choice: 'Multiple-choice',
    stage_5: 'Stage 5',
    // Game Studio Screen
    game_studio_import_title: 'Import Your Content',
    game_studio_import_desc: 'Easily create your games or assignments with AI using any material.',
    game_studio_math_title: 'Math',
    game_studio_math_desc: 'Easily create your maths games or assignments according to the curriculum and specific learning outcomes with AI.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Easily create your science games or assignments according to the curriculum and specific learning outcomes with AI.',
    // Import Wizard
    stepper_curriculum: 'Curriculum',
    stepper_stage_selection: 'Stage Selection',
    stepper_source: 'Source',
    stepper_preferences: 'Preferences',
    stepper_preview: 'Preview',
    select_curriculum: 'Select Curriculum',
    curriculum_ib: 'International Baccalaureate (IB)',
    select_stage: 'Select Stage',
    stage_1: 'Stage 1',
    stage_2: 'Stage 2',
    stage_3: 'Stage 3',
    stage_4: 'Stage 4',
    stage_6: 'Stage 6',
    upload_file_or_select_source: 'Upload File or Select Source',
    drag_drop_file: 'Drag & drop a file here to upload',
    choose_a_file: 'Choose a File',
    supported_file_types: 'Supported file types: PDF, PPT, PPTX, DOCX, DOC, XLS, XLSX, CSV, TXT, MD, RTF, JSON, XML, JPG, JPEG, PNG, GIF, BMP, WEBP',
    uploaded_files: 'Uploaded Files:',
    total_file_size: 'Total file size max. 20 MB',
    content_language: 'Content Language',
    ai_is_creating: 'AI is Creating Your Content...',
    ai_warning: 'AI can make mistakes when creating content or repeat the same questions. Do not forget to check the content on the preview step. If necessary, you can add, remove or regenerate all questions.',
    // Block Coding
    block_coding: 'Block Coding',
    block_coding_desc: 'Start with fun, colorful blocks. Perfect for beginners!',
    sequences: 'Sequences',
    loops: 'Loops',
    events: 'Events',
    maze_game: 'Maze Game',
    sequences_badge: 'Sequencer',
    loop_master_badge: 'Loop Master',
    event_expert_badge: 'Event Expert',
    maze_master_badge: 'Maze Master',
    // Python
    python: 'Python',
    python_desc: 'Jump into real-world code with the Python language.',
    python_vars_numbers: 'Variables & Numbers',
    python_loops: 'Loops',
    python_conditionals: 'Conditionals',
    python_functions: 'Functions',
    python_quiz_game: 'Mini Project: Quiz Game',
    number_ninja_badge: 'Number Ninja',
    python_looper_badge: 'Python Looper',
    function_fanatic_badge: 'Function Fanatic',
    quiz_whiz_badge: 'Quiz Whiz',
    // JavaScript
    javascript: 'JavaScript',
    javascript_desc: 'Build cool websites and apps with the language of the web.',
    js_vars_alerts: 'Variables & Alerts',
    js_dom: 'DOM Manipulation',
    js_loops_conditionals: 'Loops & Conditionals',
    js_functions_events: 'Functions & Events',
    js_interactive_story: 'Mini Project: Interactive Story',
    alerter_badge: 'Alerter',
    dom_dynamo_badge: 'DOM Dynamo',
    event_handler_badge: 'Event Handler',
    story_spinner_badge: 'Story Spinner',
    // Lua
    lua: 'Lua',
    lua_desc: 'Create powerful games and scripts with the Lua language.',
    lua_intro: 'Intro to Lua',
    lua_logic: 'Logic & Math',
    lua_functions: 'Functions',
    lua_tables: 'Tables (Arrays)',
    lua_text_adventure: 'Mini Project: Text Adventure',
    lua_printer_badge: 'Print Pro',
    lua_logic_badge: 'Logic Wizard',
    lua_function_badge: 'Function Builder',
    lua_adventure_badge: 'Adventurer',
    // Web Dev
    web_dev: 'Web Dev',
    web_dev_desc: 'Build your very first websites with HTML and CSS.',
    web_html_basics: 'HTML Basics',
    web_images_links: 'Images & Links',
    web_css_intro: 'Intro to CSS',
    web_css_layout: 'CSS Layouts',
    web_animal_page: 'Mini Project: Animal Page',
    web_tagger_badge: 'HTML Tagger',
    web_linker_badge: 'Web Linker',
    web_styler_badge: 'CSS Styler',
    web_builder_badge: 'Page Builder',
    // C++
    c_plus_plus: 'C++',
    c_plus_plus_desc: 'Master low-level memory management and performance.',
    cpp_pointers: 'Pointers & Memory',
    cpp_classes: 'Classes & Objects',
    cpp_stl: 'STL Containers',
    cpp_calculator: 'Project: Console Calculator',
    cpp_badge_pointer: 'Pointer Pro',
    cpp_badge_oop: 'Object Oriented',
    cpp_badge_stl: 'STL Master',
    cpp_badge_calculator: 'Calculator Creator',
    // C#
    c_sharp: 'C#',
    c_sharp_desc: 'Build powerful apps on the .NET platform.',
    csharp_dotnet: '.NET Basics',
    csharp_linq: 'LINQ',
    csharp_async: 'Async/Await',
    csharp_todo_app: 'Project: To-Do List App',
    csharp_badge_dotnet: '.NET Novice',
    csharp_badge_linq: 'LINQ Legend',
    csharp_badge_async: 'Async Ace',
    csharp_badge_taskmaster: 'Task Master',
    // Java
    java: 'Java',
    java_desc: 'A versatile, object-oriented language for any project.',
    java_jvm: 'JVM & Basics',
    java_oop: 'OOP Principles',
    java_collections: 'Collections Framework',
    java_bank_account: 'Project: Bank Account System',
    java_badge_jvm: 'Java Jolt',
    java_badge_oop: 'OOP Oracle',
    java_badge_collections: 'Collection King',
    java_badge_banker: 'Bank Builder',
    // Kotlin
    kotlin: 'Kotlin',
    kotlin_desc: 'Modern, concise language for Android app development.',
    kotlin_null_safety: 'Null Safety',
    kotlin_coroutines: 'Coroutines',
    kotlin_data_classes: 'Data Classes',
    kotlin_button_clicker: 'Project: Button Clicker App',
    kotlin_badge_null: 'Null Navigator',
    kotlin_badge_coroutines: 'Coroutine Captain',
    kotlin_badge_data: 'Data Dynamo',
    kotlin_badge_apprentice: 'App Apprentice',
    // Swift
    swift: 'Swift',
    swift_desc: 'Create beautiful apps for Apple devices.',
    swift_optionals: 'Optionals',
    swift_swiftui: 'SwiftUI Basics',
    swift_closures: 'Closures',
    swift_tip_calculator: 'Project: Tip Calculator',
    swift_badge_optionals: 'Optional Observer',
    swift_badge_swiftui: 'SwiftUI Stylist',
    swift_badge_closures: 'Closure Champion',
    swift_badge_tiptop: 'Tip Top Coder',
    // Go
    go: 'Go',
    go_desc: 'Fast, simple, and concurrent language from Google.',
    go_goroutines: 'Goroutines',
    go_channels: 'Channels',
    go_structs: 'Structs',
    go_web_scraper: 'Project: Web Scraper',
    go_badge_gogetter: 'Go-getter',
    go_badge_channel: 'Channel Chief',
    go_badge_struct: 'Struct Star',
    go_badge_weaver: 'Web Weaver',
    // Rust
    rust: 'Rust',
    rust_desc: 'Performance and safety for systems programming.',
    rust_ownership: 'Ownership & Borrowing',
    rust_enums: 'Enums & Matching',
    rust_lifetimes: 'Lifetimes',
    rust_word_counter: 'Project: Word Counter',
    rust_badge_ownership: 'Ownership Owner',
    rust_badge_pattern: 'Pattern Pro',
    rust_badge_lifetime: 'Lifetime Leader',
    rust_badge_cli: 'CLI Crafter',
    // PHP
    php: 'PHP',
    php_desc: 'The language that powers much of the web.',
    php_server_basics: 'Server Basics',
    php_arrays: 'Arrays',
    php_forms: 'Form Handling',
    php_contact_form: 'Project: Contact Form',
    php_badge_server: 'Server Starter',
    php_badge_array: 'Array Artist',
    php_badge_form: 'Form Fanatic',
    php_badge_contact: 'Contact Creator',
    // Ruby
    ruby: 'Ruby',
    ruby_desc: 'A dynamic language with a focus on simplicity.',
    ruby_blocks: 'Blocks & Procs',
    ruby_gems: 'Gems',
    ruby_metaprogramming: 'Metaprogramming',
    ruby_blog_generator: 'Project: Blog Generator',
    ruby_badge_block: 'Block Boss',
    ruby_badge_gem: 'Gem Guru',
    ruby_badge_meta: 'Meta Master',
    ruby_badge_blogger: 'Blog Builder',
    // TypeScript
    typescript: 'TypeScript',
    typescript_desc: 'JavaScript with the safety of types.',
    ts_types: 'Basic Types',
    ts_interfaces: 'Interfaces',
    ts_generics: 'Generics',
    ts_todo_list: 'Project: Type-Safe To-Do List',
    ts_badge_type: 'Type Titan',
    ts_badge_interface: 'Interface Inspector',
    ts_badge_generic: 'Generic Genius',
    ts_badge_scripter: 'Safe Scripter',
    // SQL
    sql: 'SQL',
    sql_desc: 'The language for managing data in databases.',
    sql_select: 'SELECT & FROM',
    sql_where: 'WHERE & ORDER BY',
    sql_joins: 'JOINs',
    sql_query_db: 'Project: Query a Database',
    sql_badge_select: 'SELECT Star',
    sql_badge_where: 'WHERE Wizard',
    sql_badge_join: 'JOIN Jedi',
    sql_badge_query: 'Query Queen',
    // R
    r: 'R',
    r_desc: 'The top language for statistics and data analysis.',
    r_data_frames: 'Data Frames',
    r_vectors: 'Vectors',
    r_plotting: 'Plotting with ggplot2',
    r_analyze_data: 'Project: Analyze a Dataset',
    r_badge_dataframe: 'Data Framer',
    r_badge_vector: 'Vector Virtuoso',
    r_badge_plot: 'Plotting Pro',
    r_badge_analyst: 'Analyst Apprentice',
    // Dart
    dart: 'Dart',
    dart_desc: 'Build apps for any screen with the Flutter framework.',
    dart_futures: 'Futures',
    dart_widgets: 'Widgets',
    dart_state: 'State Management',
    dart_counter_app: 'Project: Counter App',
    dart_badge_future: 'Future Forecaster',
    dart_badge_widget: 'Widget Whiz',
    dart_badge_state: 'State Strategist',
    dart_badge_flutter: 'Flutter Friend',
    // Scala
    scala: 'Scala',
    scala_desc: 'Combine functional and object-oriented programming.',
    scala_fp: 'Functional Programming',
    scala_case_classes: 'Case Classes',
    scala_futures: 'Futures & Promises',
    scala_data_transformer: 'Project: Data Transformer',
    scala_badge_fp: 'Functional Fan',
    scala_badge_case: 'Case Class Connoisseur',
    scala_badge_future: 'Future Fancier',
    scala_badge_transformer: 'Data Director',
  },
  fr: {
    learn: 'Apprendre',
    profile: 'Profil',
    creations: 'Créations',
    shop: 'Boutique',
    xp: 'XP',
    streak: 'Série',
    start: 'Commencer',
    locked: 'Verrouillé',
    completed: 'Terminé',
    lesson_complete: 'Leçon Terminée !',
    you_earned: 'Tu as gagné',
    continue: 'Continuer',
    exit: 'Quitter',
    login: 'Connexion',
    signUp: 'S\'inscrire',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    create_account: 'Créer un compte',
    logout: 'Déconnexion',
    welcome_back: 'Bon Retour !',
    join_the_adventure: 'Rejoins l\'aventure !',
    my_profile: 'Mon Profil',
    my_badges: 'Mes Badges',
    my_creations: 'Mes Créations',
    start_creating_prompt: 'Crée ton premier jeu pour le voir ici !',
    skip_for_now: 'Passer pour l\'instant',
    choose_your_path: 'Choisis Ton Aventure !',
    coming_soon: 'Bientôt Disponible',
    change_path: 'Changer de Voie',
    back: 'Retour',
    next: 'Suivant',
    // Creation Screen
    game_studio: 'Studio de Jeux',
    game_studio_desc: 'Créez des jeux de tableau blanc interactifs ou des devoirs sur n\'importe quel sujet avec l\'IA.',
    create: 'Créer',
    question_lab: 'Labo Questions',
    question_lab_desc: 'Générez des quiz, des questions à choix multiples ou ouvertes pour les activités en classe, les devoirs ou les documents imprimables avec l\'IA.',
    generate: 'Générer',
    smart_books: 'Livres Intelligents',
    smart_books_desc: 'Utilisez l\'IA pour créer votre propre livre ou accéder à des livres de lecture dans votre propre langue ou dans des langues étrangères.',
    open: 'Ouvrir',
    scientific_inquiry: 'Enquête Scientifique',
    scientific_inquiry_desc: 'Posez à votre sympathique compagnon IA toutes les questions que vous souhaitez et obtenez une réponse instantanée.',
    speaking_hub: 'Hub de Parole',
    speaking_hub_desc: 'Utilisez un modèle d\'IA vocal pour vous entraîner à parler une langue étrangère et améliorer vos compétences.',
    start_speaking: 'Commencer à Parler',
    recent_contents: 'Contenus Récents',
    view_all: 'Voir Tout',
    content_type: 'Type de Contenu',
    stage: 'Niveau',
    question_count: 'Nombre de Questions',
    language_label: 'Langue',
    view_learning_outcomes: 'Voir les Résultats d\'Apprentissage',
    assign: 'Assigner',
    open_content: 'Ouvrir',
    rename: 'Renommer',
    share: 'Partager',
    quiz: 'Quiz',
    multiple_choice: 'Choix multiple',
    stage_5: 'Niveau 5',
    // Game Studio Screen
    game_studio_import_title: 'Importer Votre Contenu',
    game_studio_import_desc: 'Créez facilement vos jeux ou devoirs avec l\'IA en utilisant n\'importe quel matériel.',
    game_studio_math_title: 'Maths',
    game_studio_math_desc: 'Créez facilement vos jeux de maths ou devoirs conformément au programme et aux objectifs d\'apprentissage spécifiques avec l\'IA.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Créez facilement vos jeux de science ou devoirs conformément au programme et aux objectifs d\'apprentissage spécifiques avec l\'IA.',
    // Import Wizard
    stepper_curriculum: 'Programme',
    stepper_stage_selection: 'Sélection du Niveau',
    stepper_source: 'Source',
    stepper_preferences: 'Préférences',
    stepper_preview: 'Aperçu',
    select_curriculum: 'Sélectionner le Programme',
    curriculum_ib: 'Baccalauréat International (IB)',
    select_stage: 'Sélectionner le Niveau',
    stage_1: 'Niveau 1',
    stage_2: 'Niveau 2',
    stage_3: 'Niveau 3',
    stage_4: 'Niveau 4',
    stage_6: 'Niveau 6',
    upload_file_or_select_source: 'Télécharger un Fichier ou Sélectionner une Source',
    drag_drop_file: 'Glissez et déposez un fichier ici pour le télécharger',
    choose_a_file: 'Choisir un Fichier',
    supported_file_types: 'Types de fichiers pris en charge : PDF, PPT, PPTX, DOCX, DOC, XLS, XLSX, CSV, TXT, MD, RTF, JSON, XML, JPG, JPEG, PNG, GIF, BMP, WEBP',
    uploaded_files: 'Fichiers Téléchargés:',
    total_file_size: 'Taille totale maximale du fichier : 20 Mo',
    content_language: 'Langue du Contenu',
    ai_is_creating: 'L\'IA Crée Votre Contenu...',
    ai_warning: 'L\'IA peut faire des erreurs lors de la création de contenu ou répéter les mêmes questions. N\'oubliez pas de vérifier le contenu à l\'étape de l\'aperçu. Si nécessaire, vous pouvez ajouter, supprimer ou régénérer toutes les questions.',
    // Block Coding
    block_coding: 'Code en Blocs',
    block_coding_desc: 'Commence avec des blocs amusants et colorés. Parfait pour les débutants !',
    sequences: 'Séquences',
    loops: 'Boucles',
    events: 'Événements',
    maze_game: 'Jeu du Labyrinthe',
    sequences_badge: 'Séquenceur',
    loop_master_badge: 'Maître des Boucles',
    event_expert_badge: 'Expert en Événements',
    maze_master_badge: 'Maître du Labyrinthe',
    // Python
    python: 'Python',
    python_desc: 'Plonge dans le code du monde réel avec le langage Python.',
    python_vars_numbers: 'Variables & Nombres',
    python_loops: 'Boucles',
    python_conditionals: 'Conditions',
    python_functions: 'Fonctions',
    python_quiz_game: 'Mini Projet: Jeu de Quiz',
    number_ninja_badge: 'Ninja des Nombres',
    python_looper_badge: 'Boucleur Python',
    function_fanatic_badge: 'Fan de Fonctions',
    quiz_whiz_badge: 'As du Quiz',
    // JavaScript
    javascript: 'JavaScript',
    javascript_desc: 'Crée des sites web et des applications avec le langage du web.',
    js_vars_alerts: 'Variables & Alertes',
    js_dom: 'Manipulation du DOM',
    js_loops_conditionals: 'Boucles & Conditions',
    js_functions_events: 'Fonctions & Événements',
    js_interactive_story: 'Mini Projet: Histoire Interactive',
    alerter_badge: 'Alerteur',
    dom_dynamo_badge: 'Dynamo du DOM',
    event_handler_badge: 'Gestionnaire d\'Événements',
    story_spinner_badge: 'Conteur d\'Histoires',
    // Lua
    lua: 'Lua',
    lua_desc: 'Créez des jeux et des scripts puissants avec le langage Lua.',
    lua_intro: 'Intro à Lua',
    lua_logic: 'Logique & Maths',
    lua_functions: 'Fonctions',
    lua_tables: 'Tableaux',
    lua_text_adventure: 'Mini Projet: Aventure Textuelle',
    lua_printer_badge: 'Pro de l\'Impression',
    lua_logic_badge: 'Sorcier de la Logique',
    lua_function_badge: 'Constructeur de Fonctions',
    lua_adventure_badge: 'Aventurier',
    // Web Dev
    web_dev: 'Développement Web',
    web_dev_desc: 'Construisez vos tout premiers sites web avec HTML et CSS.',
    web_html_basics: 'Bases de HTML',
    web_images_links: 'Images & Liens',
    web_css_intro: 'Intro à CSS',
    web_css_layout: 'Mises en page CSS',
    web_animal_page: 'Mini Projet: Page d\'Animal',
    web_tagger_badge: 'Tagueur HTML',
    web_linker_badge: 'Lieur Web',
    web_styler_badge: 'Styleur CSS',
    web_builder_badge: 'Constructeur de Pages',
    // C++
    c_plus_plus: 'C++',
    c_plus_plus_desc: 'Maîtrisez la gestion mémoire et la performance.',
    cpp_pointers: 'Pointeurs & Mémoire',
    cpp_classes: 'Classes & Objets',
    cpp_stl: 'Conteneurs STL',
    cpp_calculator: 'Projet: Calculatrice Console',
    cpp_badge_pointer: 'Pro des Pointeurs',
    cpp_badge_oop: 'Orienté Objet',
    cpp_badge_stl: 'Maître STL',
    cpp_badge_calculator: 'Créateur de Calculatrice',
    // C#
    c_sharp: 'C#',
    c_sharp_desc: 'Créez des applications puissantes sur la plateforme .NET.',
    csharp_dotnet: 'Bases de .NET',
    csharp_linq: 'LINQ',
    csharp_async: 'Async/Await',
    csharp_todo_app: 'Projet: App de Tâches',
    csharp_badge_dotnet: 'Novice .NET',
    csharp_badge_linq: 'Légende LINQ',
    csharp_badge_async: 'As de l\'Async',
    csharp_badge_taskmaster: 'Maître des Tâches',
    // Java
    java: 'Java',
    java_desc: 'Un langage polyvalent et orienté objet pour tout projet.',
    java_jvm: 'JVM & Bases',
    java_oop: 'Principes POO',
    java_collections: 'Framework de Collections',
    java_bank_account: 'Projet: Compte Bancaire',
    java_badge_jvm: 'Choc Java',
    java_badge_oop: 'Oracle POO',
    java_badge_collections: 'Roi des Collections',
    java_badge_banker: 'Constructeur de Banque',
    // Kotlin
    kotlin: 'Kotlin',
    kotlin_desc: 'Langage moderne pour le développement Android.',
    kotlin_null_safety: 'Sécurité Nulle',
    kotlin_coroutines: 'Coroutines',
    kotlin_data_classes: 'Classes de Données',
    kotlin_button_clicker: 'Projet: Clicker de Bouton',
    kotlin_badge_null: 'Navigateur Nul',
    kotlin_badge_coroutines: 'Capitaine Coroutine',
    kotlin_badge_data: 'Dynamo de Données',
    kotlin_badge_apprentice: 'Apprenti d\'App',
    // Swift
    swift: 'Swift',
    swift_desc: 'Créez de belles applications pour les appareils Apple.',
    swift_optionals: 'Optionnels',
    swift_swiftui: 'Bases de SwiftUI',
    swift_closures: 'Closures',
    swift_tip_calculator: 'Projet: Calculateur de Pourboire',
    swift_badge_optionals: 'Observateur d\'Optionnels',
    swift_badge_swiftui: 'Styliste SwiftUI',
    swift_badge_closures: 'Champion des Closures',
    swift_badge_tiptop: 'Codeur au Top',
    // Go
    go: 'Go',
    go_desc: 'Langage rapide, simple et concurrent de Google.',
    go_goroutines: 'Goroutines',
    go_channels: 'Canaux',
    go_structs: 'Structures',
    go_web_scraper: 'Projet: Gratteur Web',
    go_badge_gogetter: 'Débrouillard',
    go_badge_channel: 'Chef de Canal',
    go_badge_struct: 'Star des Structures',
    go_badge_weaver: 'Tisseur du Web',
    // Rust
    rust: 'Rust',
    rust_desc: 'Performance et sécurité pour la programmation système.',
    rust_ownership: 'Possession & Emprunt',
    rust_enums: 'Enums & Correspondance',
    rust_lifetimes: 'Durées de Vie',
    rust_word_counter: 'Projet: Compteur de Mots',
    rust_badge_ownership: 'Propriétaire de la Possession',
    rust_badge_pattern: 'Pro du Pattern',
    rust_badge_lifetime: 'Leader de Durée de Vie',
    rust_badge_cli: 'Artisan CLI',
    // PHP
    php: 'PHP',
    php_desc: 'Le langage qui alimente une grande partie du web.',
    php_server_basics: 'Bases du Serveur',
    php_arrays: 'Tableaux',
    php_forms: 'Gestion de Formulaires',
    php_contact_form: 'Projet: Formulaire de Contact',
    php_badge_server: 'Débutant Serveur',
    php_badge_array: 'Artiste des Tableaux',
    php_badge_form: 'Fan de Formulaires',
    php_badge_contact: 'Créateur de Contacts',
    // Ruby
    ruby: 'Ruby',
    ruby_desc: 'Un langage dynamique axé sur la simplicité.',
    ruby_blocks: 'Blocs & Procs',
    ruby_gems: 'Gemmes',
    ruby_metaprogramming: 'Métaprogrammation',
    ruby_blog_generator: 'Projet: Générateur de Blog',
    ruby_badge_block: 'Boss des Blocs',
    ruby_badge_gem: 'Gourou des Gemmes',
    ruby_badge_meta: 'Maître Méta',
    ruby_badge_blogger: 'Constructeur de Blog',
    // TypeScript
    typescript: 'TypeScript',
    typescript_desc: 'JavaScript avec la sécurité des types.',
    ts_types: 'Types de Base',
    ts_interfaces: 'Interfaces',
    ts_generics: 'Génériques',
    ts_todo_list: 'Projet: Liste de Tâches Typée',
    ts_badge_type: 'Titan des Types',
    ts_badge_interface: 'Inspecteur d\'Interfaces',
    ts_badge_generic: 'Génie des Génériques',
    ts_badge_scripter: 'Scripteur Sûr',
    // SQL
    sql: 'SQL',
    sql_desc: 'Le langage pour gérer les données dans les bases de données.',
    sql_select: 'SELECT & FROM',
    sql_where: 'WHERE & ORDER BY',
    sql_joins: 'JOINs',
    sql_query_db: 'Projet: Interroger une Base de Données',
    sql_badge_select: 'Étoile du SELECT',
    sql_badge_where: 'Sorcier du WHERE',
    sql_badge_join: 'Jedi du JOIN',
    sql_badge_query: 'Reine des Requêtes',
    // R
    r: 'R',
    r_desc: 'Le langage de choix pour les statistiques et l\'analyse de données.',
    r_data_frames: 'Data Frames',
    r_vectors: 'Vecteurs',
    r_plotting: 'Graphiques avec ggplot2',
    r_analyze_data: 'Projet: Analyser un jeu de données',
    r_badge_dataframe: 'Cadreur de Données',
    r_badge_vector: 'Virtuose des Vecteurs',
    r_badge_plot: 'Pro des Graphiques',
    r_badge_analyst: 'Analyste Apprenti',
    // Dart
    dart: 'Dart',
    dart_desc: 'Créez des applications pour tous les écrans avec Flutter.',
    dart_futures: 'Futures',
    dart_widgets: 'Widgets',
    dart_state: 'Gestion d\'État',
    dart_counter_app: 'Projet: App Compteur',
    dart_badge_future: 'Prédicteur de Futures',
    dart_badge_widget: 'As des Widgets',
    dart_badge_state: 'Stratège de l\'État',
    dart_badge_flutter: 'Ami de Flutter',
    // Scala
    scala: 'Scala',
    scala_desc: 'Combinez la programmation fonctionnelle et orientée objet.',
    scala_fp: 'Programmation Fonctionnelle',
    scala_case_classes: 'Classes de Cas',
    scala_futures: 'Futures & Promesses',
    scala_data_transformer: 'Projet: Transformateur de Données',
    scala_badge_fp: 'Fan du Fonctionnel',
    scala_badge_case: 'Connaisseur des Case Classes',
    scala_badge_future: 'Amateur de Futures',
    scala_badge_transformer: 'Directeur de Données',
  },
  ar: {
    learn: 'تعلم',
    profile: 'ملف شخصي',
    creations: 'إبداعات',
    shop: 'متجر',
    xp: 'نقطة',
    streak: 'سلسلة',
    start: 'ابدأ',
    locked: 'مغلق',
    completed: 'مكتمل',
    lesson_complete: 'اكتمل الدرس!',
    you_earned: 'لقد حصلت على',
    continue: 'متابعة',
    exit: 'خروج',
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    create_account: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    welcome_back: 'مرحبا بعودتك!',
    join_the_adventure: 'انضم إلى المغامرة!',
    my_profile: 'ملفي الشخصي',
    my_badges: 'شاراتي',
    my_creations: 'إبداعاتي',
    start_creating_prompt: 'أنشئ أول لعبة لك لرؤيتها هنا!',
    skip_for_now: 'تخطى في الوقت الحالي',
    choose_your_path: 'اختر مسارك!',
    coming_soon: 'قريباً',
    change_path: 'تغيير المسار',
    back: 'رجوع',
    next: 'التالي',
    // Creation Screen
    game_studio: 'ستوديو الألعاب',
    game_studio_desc: 'أنشئ ألعاب سبورة بيضاء تفاعلية أو واجبات حول أي موضوع باستخدام الذكاء الاصطناعي.',
    create: 'إنشاء',
    question_lab: 'مختبر الأسئلة',
    question_lab_desc: 'أنشئ اختبارات قصيرة أو أسئلة متعددة الخيارات أو مفتوحة للأنشطة الصفية أو الواجبات المنزلية أو المواد القابلة للطباعة باستخدام الذكاء الاصطناعي.',
    generate: 'توليد',
    smart_books: 'الكتب الذكية',
    smart_books_desc: 'استخدم الذكاء الاصطناعي لإنشاء كتابك الخاص أو الوصول إلى كتب القراءة بلغتك أو بلغات أجنبية.',
    open: 'فتح',
    scientific_inquiry: 'البحث العلمي',
    scientific_inquiry_desc: 'اسأل رفيقك الذكي الاصطناعي أي سؤال تريده واحصل على إجابة فورية.',
    speaking_hub: 'مركز التحدث',
    speaking_hub_desc: 'استخدم نموذجًا صوتيًا قائمًا على الذكاء الاصطناعي لممارسة التحدث بلغة أجنبية وتحسين مهاراتك.',
    start_speaking: 'ابدأ التحدث',
    recent_contents: 'المحتويات الأخيرة',
    view_all: 'عرض الكل',
    content_type: 'نوع المحتوى',
    stage: 'المرحلة',
    question_count: 'عدد الأسئلة',
    language_label: 'اللغة',
    view_learning_outcomes: 'عرض مخرجات التعلم',
    assign: 'تعيين',
    open_content: 'فتح',
    rename: 'إعادة تسمية',
    share: 'مشاركة',
    quiz: 'اختبار',
    multiple_choice: 'متعدد الخيارات',
    stage_5: 'المرحلة 5',
    // Game Studio Screen
    game_studio_import_title: 'استيراد المحتوى الخاص بك',
    game_studio_import_desc: 'أنشئ ألعابك أو واجباتك بسهولة باستخدام الذكاء الاصطناعي باستخدام أي مادة.',
    game_studio_math_title: 'رياضيات',
    game_studio_math_desc: 'أنشئ ألعاب الرياضيات أو الواجبات بسهولة وفقًا للمنهج الدراسي ومخرجات التعلم المحددة باستخدام الذكاء الاصطناعي.',
    game_studio_science_title: 'علوم',
    game_studio_science_desc: 'أنشئ ألعاب العلوم أو الواجبات بسهولة وفقًا للمنهج الدراسي ومخرجات التعلم المحددة باستخدام الذكاء الاصطناعي.',
    // Import Wizard
    stepper_curriculum: 'المنهج الدراسي',
    stepper_stage_selection: 'اختيار المرحلة',
    stepper_source: 'المصدر',
    stepper_preferences: 'التفضيلات',
    stepper_preview: 'معاينة',
    select_curriculum: 'اختر المنهج الدراسي',
    curriculum_ib: 'البكالوريا الدولية (IB)',
    select_stage: 'اختر المرحلة',
    stage_1: 'المرحلة 1',
    stage_2: 'المرحلة 2',
    stage_3: 'المرحلة 3',
    stage_4: 'المرحلة 4',
    stage_6: 'المرحلة 6',
    upload_file_or_select_source: 'تحميل ملف أو اختيار مصدر',
    drag_drop_file: 'اسحب وأفلت ملفًا هنا للتحميل',
    choose_a_file: 'اختر ملفًا',
    supported_file_types: 'أنواع الملفات المدعومة: PDF, PPT, PPTX, DOCX, DOC, XLS, XLSX, CSV, TXT, MD, RTF, JSON, XML, JPG, JPEG, PNG, GIF, BMP, WEBP',
    uploaded_files: 'الملفات المرفوعة:',
    total_file_size: 'الحد الأقصى لحجم الملف 20 ميجابايت',
    content_language: 'لغة المحتوى',
    ai_is_creating: 'يقوم الذكاء الاصطناعي بإنشاء المحتوى الخاص بك...',
    ai_warning: 'يمكن للذكاء الاصطناعي أن يرتكب أخطاء عند إنشاء المحتوى أو يكرر نفس الأسئلة. لا تنس التحقق من المحتوى في خطوة المعاينة. إذا لزم الأمر ، يمكنك إضافة أو إزالة أو إعادة إنشاء جميع الأسئلة.',
    // Block Coding
    block_coding: 'البرمجة بالبلوكات',
    block_coding_desc: 'ابدأ بكتل ممتعة وملونة. مثالية للمبتدئين!',
    sequences: 'التسلسلات',
    loops: 'الحلقات',
    events: 'الأحداث',
    maze_game: 'لعبة المتاهة',
    sequences_badge: 'متسلسل',
    loop_master_badge: 'محترف الحلقات',
    event_expert_badge: 'خبير الأحداث',
    maze_master_badge: 'محترف المتاهة',
    // Python
    python: 'بايثون',
    python_desc: 'ادخل إلى عالم البرمجة الحقيقي باستخدام لغة باython.',
    python_vars_numbers: 'المتغيرات والأرقام',
    python_loops: 'الحلقات',
    python_conditionals: 'الشروط',
    python_functions: 'الدوال',
    python_quiz_game: 'مشروع صغير: لعبة اختبار',
    number_ninja_badge: 'نينجا الأرقام',
    python_looper_badge: 'محترف حلقات بايثون',
    function_fanatic_badge: 'مهووس الدوال',
    quiz_whiz_badge: 'نجم الاختبارات',
    // JavaScript
    javascript: 'جافاسكريبت',
    javascript_desc: 'أنشئ مواقع وتطبيقات رائعة بلغة الويب.',
    js_vars_alerts: 'المتغيرات والتنبيهات',
    js_dom: 'التحكم في DOM',
    js_loops_conditionals: 'الحلقات والشروط',
    js_functions_events: 'الدوال والأحداث',
    js_interactive_story: 'مشروع صغير: قصة تفاعلية',
    alerter_badge: 'منبه',
    dom_dynamo_badge: 'دينامو الـ DOM',
    event_handler_badge: 'معالج الأحداث',
    story_spinner_badge: 'راوي القصص',
    // Lua
    lua: 'لوا',
    lua_desc: 'أنشئ ألعابًا ونصوصًا قوية باستخدام لغة لوا.',
    lua_intro: 'مقدمة في لوا',
    lua_logic: 'المنطق والرياضيات',
    lua_functions: 'الدوال',
    lua_tables: 'الجداول (المصفوفات)',
    lua_text_adventure: 'مشروع صغير: مغامرة نصية',
    lua_printer_badge: 'محترف الطباعة',
    lua_logic_badge: 'ساحر المنطق',
    lua_function_badge: 'منشئ الدوال',
    lua_adventure_badge: 'مغامر',
    // Web Dev
    web_dev: 'تطوير الويب',
    web_dev_desc: 'ابنِ أول مواقع الويب الخاصة بك باستخدام HTML و CSS.',
    web_html_basics: 'أساسيات HTML',
    web_images_links: 'الصور والروابط',
    web_css_intro: 'مقدمة في CSS',
    web_css_layout: 'تخطيطات CSS',
    web_animal_page: 'مشروع صغير: صفحة حيوان',
    web_tagger_badge: 'واسم HTML',
    web_linker_badge: 'رابط الويب',
    web_styler_badge: 'منسق CSS',
    web_builder_badge: 'منشئ الصفحات',
    // C++
    c_plus_plus: 'C++',
    c_plus_plus_desc: 'أتقن إدارة الذاكرة والأداء منخفض المستوى.',
    cpp_pointers: 'المؤشرات والذاكرة',
    cpp_classes: 'الفئات والكائنات',
    cpp_stl: 'حاويات STL',
    cpp_calculator: 'مشروع: آلة حاسبة',
    cpp_badge_pointer: 'محترف المؤشرات',
    cpp_badge_oop: 'كائني التوجه',
    cpp_badge_stl: 'سيد STL',
    cpp_badge_calculator: 'صانع الآلة الحاسبة',
    // C#
    c_sharp: 'C#',
    c_sharp_desc: 'ابنِ تطبيقات قوية على منصة .NET.',
    csharp_dotnet: 'أساسيات .NET',
    csharp_linq: 'LINQ',
    csharp_async: 'Async/Await',
    csharp_todo_app: 'مشروع: تطبيق قائمة مهام',
    csharp_badge_dotnet: 'مبتدئ .NET',
    csharp_badge_linq: 'أسطورة LINQ',
    csharp_badge_async: 'خبير Async',
    csharp_badge_taskmaster: 'سيد المهام',
    // Java
    java: 'جافا',
    java_desc: 'لغة متعددة الاستخدامات وموجهة للكائنات لأي مشروع.',
    java_jvm: 'JVM والأساسيات',
    java_oop: 'مبادئ OOP',
    java_collections: 'إطار المجموعات',
    java_bank_account: 'مشروع: نظام حساب بنكي',
    java_badge_jvm: 'صدمة جافا',
    java_badge_oop: 'حكيم OOP',
    java_badge_collections: 'ملك المجموعات',
    java_badge_banker: 'باني البنوك',
    // Kotlin
    kotlin: 'كوتلن',
    kotlin_desc: 'لغة حديثة وموجزة لتطوير تطبيقات أندرويد.',
    kotlin_null_safety: 'السلامة من Null',
    kotlin_coroutines: 'Coroutines',
    kotlin_data_classes: 'فئات البيانات',
    kotlin_button_clicker: 'مشروع: تطبيق النقر على الزر',
    kotlin_badge_null: 'ملاح Null',
    kotlin_badge_coroutines: 'قبطان Coroutine',
    kotlin_badge_data: 'دينامو البيانات',
    kotlin_badge_apprentice: 'متدرب التطبيقات',
    // Swift
    swift: 'سويفت',
    swift_desc: 'أنشئ تطبيقات جميلة لأجهزة آبل.',
    swift_optionals: 'Optionals',
    swift_swiftui: 'أساسيات SwiftUI',
    swift_closures: 'Closures',
    swift_tip_calculator: 'مشروع: حاسبة الإكرامية',
    swift_badge_optionals: 'مراقب Optionals',
    swift_badge_swiftui: 'منسق SwiftUI',
    swift_badge_closures: 'بطل Closures',
    swift_badge_tiptop: 'مبرمج القمة',
    // Go
    go: 'Go',
    go_desc: 'لغة سريعة وبسيطة ومتزامنة من جوجل.',
    go_goroutines: 'Goroutines',
    go_channels: 'القنوات',
    go_structs: 'الهياكل',
    go_web_scraper: 'مشروع: كاشط الويب',
    go_badge_gogetter: 'طموح',
    go_badge_channel: 'رئيس القنوات',
    go_badge_struct: 'نجم الهياكل',
    go_badge_weaver: 'حائك الويب',
    // Rust
    rust: 'Rust',
    rust_desc: 'الأداء والأمان لبرمجة الأنظمة.',
    rust_ownership: 'الملكية والاستعارة',
    rust_enums: 'Enums والمطابقة',
    rust_lifetimes: 'Lifetimes',
    rust_word_counter: 'مشروع: عداد الكلمات',
    rust_badge_ownership: 'مالك الملكية',
    rust_badge_pattern: 'محترف الأنماط',
    rust_badge_lifetime: 'قائد Lifetimes',
    rust_badge_cli: 'صانع CLI',
    // PHP
    php: 'PHP',
    php_desc: 'اللغة التي تشغل جزءًا كبيرًا من الويب.',
    php_server_basics: 'أساسيات الخادم',
    php_arrays: 'المصفوفات',
    php_forms: 'التعامل مع النماذج',
    php_contact_form: 'مشروع: نموذج اتصال',
    php_badge_server: 'مبتدئ الخادم',
    php_badge_array: 'فنان المصفوفات',
    php_badge_form: 'مهووس النماذج',
    php_badge_contact: 'صانع جهات الاتصال',
    // Ruby
    ruby: 'روبي',
    ruby_desc: 'لغة ديناميكية تركز على البساطة.',
    ruby_blocks: 'الكتل والإجراءات',
    ruby_gems: 'الجواهر',
    ruby_metaprogramming: 'البرمجة الوصفية',
    ruby_blog_generator: 'مشروع: مولد تدوينات',
    ruby_badge_block: 'سيد الكتل',
    ruby_badge_gem: 'خبير الجواهر',
    ruby_badge_meta: 'سيد Metaprogramming',
    ruby_badge_blogger: 'باني المدونات',
    // TypeScript
    typescript: 'TypeScript',
    typescript_desc: 'جافاسكريبت مع أمان الأنواع.',
    ts_types: 'الأنواع الأساسية',
    ts_interfaces: 'الواجهات',
    ts_generics: 'العموميات',
    ts_todo_list: 'مشروع: قائمة مهام آمنة النوع',
    ts_badge_type: 'عملاق الأنواع',
    ts_badge_interface: 'مفتش الواجهات',
    ts_badge_generic: 'عبقري العموميات',
    ts_badge_scripter: 'كاتب آمن',
    // SQL
    sql: 'SQL',
    sql_desc: 'لغة إدارة البيانات في قواعد البيانات.',
    sql_select: 'SELECT و FROM',
    sql_where: 'WHERE و ORDER BY',
    sql_joins: 'JOINs',
    sql_query_db: 'مشروع: استعلام قاعدة بيانات',
    sql_badge_select: 'نجم SELECT',
    sql_badge_where: 'ساحر WHERE',
    sql_badge_join: 'جيداي JOIN',
    sql_badge_query: 'ملكة الاستعلامات',
    // R
    r: 'R',
    r_desc: 'اللغة الأولى للإحصاء وتحليل البيانات.',
    r_data_frames: 'إطارات البيانات',
    r_vectors: 'المتجهات',
    r_plotting: 'الرسم البياني بـ ggplot2',
    r_analyze_data: 'مشروع: تحليل مجموعة بيانات',
    r_badge_dataframe: 'مؤطر البيانات',
    r_badge_vector: 'فنان المتجهات',
    r_badge_plot: 'محترف الرسم البياني',
    r_badge_analyst: 'محلل متدرب',
    // Dart
    dart: 'Dart',
    dart_desc: 'ابنِ تطبيقات لأي شاشة باستخدام إطار Flutter.',
    dart_futures: 'Futures',
    dart_widgets: 'Widgets',
    dart_state: 'إدارة الحالة',
    dart_counter_app: 'مشروع: تطبيق عداد',
    dart_badge_future: 'متنبئ المستقبل',
    dart_badge_widget: 'خبير Widgets',
    dart_badge_state: 'استراتيجي الحالة',
    dart_badge_flutter: 'صديق Flutter',
    // Scala
    scala: 'Scala',
    scala_desc: 'اجمع بين البرمجة الوظيفية والشيئية.',
    scala_fp: 'البرمجة الوظيفية',
    scala_case_classes: 'Case Classes',
    scala_futures: 'Futures & Promises',
    scala_data_transformer: 'مشروع: محول بيانات',
    scala_badge_fp: 'محبي الوظيفية',
    scala_badge_case: 'خبير Case Classes',
    scala_badge_future: 'هاوي Futures',
    scala_badge_transformer: 'مدير البيانات',
  },
};

type TranslationKey = keyof (typeof translations)['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// FIX: Changed component definition to use React.FC for consistency and to resolve type inference issues.
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(Language.EN);

  useEffect(() => {
    const dir = language === Language.AR ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language]);

  const t = (key: TranslationKey) => {
    return translations[language][key] || translations.en[key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
