
import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';
import { Language } from '../types';

const translations = {
  en: {
    path: '/en',
    home: 'Home',
    learn: 'Learn Code',
    profile: 'Profile',
    creations: 'Creations',
    shop: 'Shop',
    xp: 'XP',
    streak: 'Streak',
    start: 'Start',
    locked: 'Locked',
    completed: 'Completed',
    lesson_complete: 'Lesson Complete!',
    you_earned: 'You earned',
    continue: 'Continue',
    exit: 'Exit',
    login: 'Login',
    signUp: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    create_account: 'Create Account',
    or_continue_with: 'OR',
    continue_with_google: 'Continue with Google',
    logout: 'Logout',
    welcome_back: 'Welcome Back!',
    join_the_adventure: 'Join the Adventure!',
    my_profile: 'My Profile',
    my_badges: 'My Badges',
    my_creations: 'My Creations',
    start_creating_prompt: 'Create your first game to see it here!',
    skip_for_now: 'Skip for now',
    choose_your_path: 'Choose Your Path!',
    coming_soon: 'Coming Soon',
    change_path: 'Change Path',
    back: 'Back',
    next: 'Next',
    search_lessons: 'Search lessons...',
    goals: 'Goals',
    leaderboard: 'Leaderboard',
    store: 'Store',
    settings: 'Settings',
    settings_language_desc: 'Choose the language for the application interface.',
    appearance: 'Appearance',
    light_mode: 'Light Mode',
    dark_mode: 'Dark Mode',
    stepper_learning_outcomes: 'Learning Outcomes',
    upload_file_or_select_source: 'Upload File or Select Source',
    drag_drop_file: 'Drag & drop a file here',
    choose_a_file: 'Choose a file',
    supported_file_types: 'Supported types: PDF, DOCX, TXT',
    uploaded_files: 'Uploaded Files',
    total_file_size: 'Total Size',
    content_language: 'Content Language',
    ai_creating_quiz: 'AI is creating your quiz...',
    ai_warning: 'This may take a few seconds.',
    stepper_preview: 'Preview',
    challenge: 'Challenge',
    run_code: 'Run Code',
    language_english: 'English',
    language_french: 'French',
    language_arabic: 'Arabic',
    speaking_wizard_duration_title: 'Conversation Duration',
    appearance_desc: 'Switch between light and dark mode to keep your eyes happy!',
    wip: '(WIP)',
    // Home Hub
    welcome_message: 'Ready for your next coding adventure?',
    magic_found: "I've found some magic for you! 🪄",
    day_streak: 'Day Streak',
    total_xp_label: 'Total XP',
    learn_adventure_desc: 'Unlock new worlds and master magic code spells!',
    create_adventure_desc: 'Use your powers to build games and stories!',
    did_you_know: 'Did you know?',
    code_fact: 'Code is just a list of instructions for your robot friend!',
    // Brain Training
    brain_training: 'Brain Training',
    brain_training_challenges: 'Challenges',
    brain_training_workouts: 'Workouts',
    brain_training_desc: 'Train your mind with fun challenges!',
    brain_training_play: 'Play',
    brain_training_back: 'Back',
    brain_training_challenges_info: 'Challenges help you see your progress and ranking. Each test reveals what you know and what to work on.',
    brain_training_workouts_info: 'Brain Workouts improve your skills. Explore all categories for balanced progress.',
    brain_training_next_level: 'Take Your Brain Training to the Next Level!',
    brain_training_unlock: 'Unlock All Features',
    brain_training_unlimited_access: 'Get unlimited access to all challenges',
    brain_training_unlimited_workouts: 'Train freely with unlimited brain workouts',
    brain_training_strengths: 'See your strengths and areas to improve',
    brain_training_ai_tips: 'Get smart improvement tips from AI',
    brain_training_new_puzzles: 'Challenge yourself with new brain puzzles',
    brain_training_premium: 'Enjoy all premium features across the platform',
    brain_training_all_challenges: 'All Challenges',
    brain_training_free_tries: 'Free Challenge Tries Left',
    brain_training_questions: 'Questions',
    brain_training_previous: 'Previous',
    brain_training_next_challenge: 'Next Challenge',
    brain_training_finish: 'Finish',
    brain_training_math: 'Math',
    brain_training_logic: 'Logic',
    brain_training_problem_solving: 'Problem Solving',
    // Quiz Play
    perfect_score: 'Perfect!',
    well_done: 'Well Done!',
    mission_accomplished: 'Mission Accomplished',
    questions_correct: 'Questions Correct',
    return_to_hub: 'Return to Hub',
    choose_magic_spell: 'Choose the right magic spell!',
    check_answer: 'Check Answer',
    amazing_feedback: 'Amazing!',
    correct_answer_label: 'Correct answer:',
    keep_up_magic: 'Keep up the magic!',
    // Lesson Screen
    genius: 'GENIUS!',
    mission_complete_msg: 'You completed the mission!',
    star_xp_units: 'STAR XP',
    next_adventure: 'Next Adventure!',
    code_editor_title: 'Code Editor',
    running: 'Running...',
    solution: 'Solution',
    use_this_code: 'Use this code',
    im_a_teacher: "I'm a teacher",
    im_a_student: "I'm a student",
    // Wizard
    last_details: 'Last Details',
    questions_label: 'Questions',
    generate_magic: 'GENERATE WITH MAGIC',
    save_creation: 'SAVE CREATION',
    consulting_ai: 'Consulting the AI Teachers...',
    back_button: 'BACK',
    continue_button: 'CONTINUE',
    // Creations
    no_content_saved: 'No content saved yet.',
    vault_empty: 'Your magic vault is empty.',
    start_creating_now: 'Create something in the Game Studio to get started!',
    view_all: 'View All',
    recent_contents: 'Recent Contents',
    content_type: 'Content Type',
    stage: 'Stage',
    question_count: 'Question Count',
    language_label: 'Language',
    view_learning_outcomes: 'View Learning Outcomes',
    assign: 'Assign',
    open_content: 'Open',
    rename: 'Rename',
    share: 'Share',
    quiz: 'Quiz',
    multiple_choice: 'Multiple-choice',
    // Profile
    following: 'Following',
    followers: 'Followers',
    league_label: 'League',
    no_bio: 'No bio yet. Ready for adventure!',
    unlocked_status: 'UNLOCKED',
    locked_status: 'LOCKED',
    edit_profile: 'Edit Profile',
    cancel: 'Cancel',
    save: 'Save',
    name_label: 'Name',
    bio_label: 'Bio',
    // Others
    type_or_talk: 'Type or talk...',
    time_left: 'Time left',
    // Curriculum
    curriculum_moroccan: 'Moroccan National Curriculum',
    curriculum_ib: 'International Baccalaureate (IB)',
    curriculum_us_core: 'U.S. Core Standards',
    stage_preschool: 'Preschool (4-5 yrs)',
    stage_primary: 'Primary Education (6 yrs)',
    stage_lower_secondary: 'Lower Secondary (3 yrs)',
    stage_upper_secondary: 'Upper Secondary (3 yrs)',
    select_curriculum: 'Select Curriculum',
    select_stage: 'Select Stage',
    stage_1: 'Stage 1',
    stage_2: 'Stage 2',
    stage_3: 'Stage 3',
    stage_4: 'Stage 4',
    stage_5: 'Stage 5',
    stage_6: 'Stage 6',
    // Game Studio Screen
    game_studio: 'Game Studio',
    game_studio_desc: 'Create interactive whiteboard games or assignments on any subject with AI.',
    create: 'Create',
    game_studio_import_title: 'Import Your Content',
    game_studio_import_desc: 'Easily create your games or assignments with AI using any material.',
    game_studio_math_title: 'Math',
    game_studio_math_desc: 'Easily create your maths games or assignments according to the curriculum and specific learning outcomes with AI.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Easily create your science games or assignments according to the curriculum and specific learning outcomes with AI.',
    game_studio_french_title: 'French',
    game_studio_french_desc: 'Easily create your French language games or assignments according to the curriculum and specific learning outcomes with AI.',
    // Question Lab Screen
    question_lab: 'Question Lab',
    question_lab_desc: 'Generate quizzes, multiple-choice or open-ended questions for activities with AI.',
    generate: 'Generate',
    question_lab_import_desc: 'Easily create practice questions, quizzes, tests, or assignments with AI using any material.',
    question_lab_math_desc: 'Easily create math questions, quizzes, tests, or assignments according to the curriculum with AI.',
    question_lab_science_desc: 'Easily create your science questions, quizzes, tests, or assignments according to the curriculum with AI.',
    question_lab_french_desc: 'Easily create your French language questions, quizzes, tests, or assignments according to the curriculum with AI.',
    // Smart Books
    smart_books: 'Smart Books',
    smart_books_desc: 'Use AI to create your own book or access reading books in your language.',
    smart_books_audiobooks_title: 'Listen to Audiobooks',
    smart_books_audiobooks_desc: 'Discover new stories and spark your imagination along the way.',
    smart_books_create_title: 'Create Your Own Book',
    smart_books_create_desc: 'Use AI to write, illustrate, and publish your own magical stories.',
    open: 'Open',
    // Scientific Inquiry
    scientific_inquiry: 'Scientific Inquiry',
    scientific_inquiry_desc: 'Explore the wonders of science with interactive experiments.',
    // Speaking Hub
    speaking_hub: 'Speaking Hub',
    speaking_hub_desc: 'Practice speaking a foreign language and improve your skills with AI.',
    start_speaking: 'Start Speaking',
    speaking_wizard_level: 'Level',
    speaking_wizard_age: 'Age',
    speaking_wizard_subject: 'Subject',
    speaking_wizard_duration: 'Duration',
    speaking_wizard_duration_mins: 'mins',
    speaking_wizard_topic_title: 'Topic',
    speaking_hub_english_american: 'English (US)',
    speaking_hub_english_british: 'English (UK)',
    speaking_hub_french: 'French',
    speaking_hub_arabic: 'Arabic',
    // ... paths ...
    // Paths
    paths: 'Paths',
    block_coding: 'Block Coding',
    block_coding_desc: 'Start with fun, colorful blocks. Perfect for beginners!',
    sequences: 'Sequences',
    loops: 'Loops',
    events: 'Events',
    maze_game: 'Maze Game',
    logic: 'Logic',
    conditionals: 'Conditionals',
    variables: 'Variables',
    logic_master: 'Logic Master',
    python: 'Python',
    python_desc: 'Jump into real-world code with the Python language.',
    javascript: 'JavaScript',
    javascript_desc: 'Build cool websites and apps with the language of the web.',
    lua: 'Lua',
    lua_desc: 'Create powerful games and scripts with the Lua language.',
    web_dev: 'Web Dev',
    web_dev_desc: 'Build your very first websites with HTML and CSS.',
    python_data_structures: 'Data Structures',
    // Python lesson titles
    python_vars_numbers: 'Variables & Numbers',
    python_loops: 'Loops',
    python_conditionals: 'Conditionals',
    python_functions: 'Functions',
    python_lists: 'Lists',
    python_dicts: 'Dictionaries',
    python_tuples: 'Tuples',
    // JavaScript lesson titles
    js_vars_alerts: 'Variables & Console',
    js_dom: 'The DOM',
    js_loops_conditionals: 'Loops & If/Else',
    js_functions_events: 'Functions & Events',
    js_interactive_story: 'Interactive Story',
    js_async_title: 'Asynchronous JS',
    js_promises: 'Promises',
    js_async_await: 'Async/Await',
    js_fetch_api: 'Fetch API',
    // Web Dev lesson titles
    web_html_basics: 'HTML Basics',
    web_images_links: 'Images & Links',
    web_css_intro: 'CSS Intro',
    web_css_layout: 'CSS Layout',
    web_animal_page: 'Animal Page Project',
    web_advanced_title: 'Advanced Layouts',
    web_flexbox: 'Flexbox',
    web_grid: 'CSS Grid',
    web_responsive_design: 'Responsive Design',
    // C++ lesson titles
    cpp_advanced_title: 'Advanced C++',
    cpp_templates: 'Templates',
    cpp_memory: 'Memory Management',
    cpp_quiz_adv: 'Advanced Quiz',

    // ─── Chapter 3 section titles ─────────────────────────────────────────────
    py_ch3_title: 'Code Like a Pro',
    js_ch3_title: 'DOM, APIs & Beyond',
    web_ch3_title: 'Interactive & Responsive Web',

    // ─── Python Chapter 3 lesson titles ──────────────────────────────────────
    python_oop: 'Object-Oriented Python',
    python_string_methods: 'String Methods',
    python_error_handling: 'Error Handling',
    python_list_comprehensions: 'List Comprehensions',
    python_recursion: 'Recursion',
    python_modules: 'Modules & Imports',
    python_final_project: '🏆 Python Final Project',

    // Python Chapter 3 — challenge descriptions
    py_challenge_9: 'Define a Dog class with a name attribute. Create an instance and print the dog\'s name.',
    py_challenge_10: 'Use Python\'s built-in string methods to convert text to UPPERCASE.',
    py_challenge_11: 'Use try/except to gracefully catch a ZeroDivisionError.',
    py_challenge_12: 'Use a one-liner list comprehension to generate squares of numbers 1-5.',
    py_challenge_13: 'Write a recursive function that prints numbers 1 to 3.',
    py_challenge_14: 'Import the built-in math module and print the square root of 16.',
    py_challenge_15: 'Mini game: compare a guess against a secret number and print the result.',

    // Python Chapter 3 — hints
    py_hint_9: 'Use self.name inside __init__ to store the attribute.',
    py_hint_10: 'Call .upper() directly on a string literal.',
    py_hint_11: 'Wrap the risky line inside try:, then handle it in except ZeroDivisionError:',
    py_hint_12: 'Syntax: [x**2 for x in range(1, 6)]',
    py_hint_13: 'Check if n > 3 to stop the recursion.',
    py_hint_14: 'import math, then call math.sqrt()',
    py_hint_15: 'Use if guess == secret: to check the answer.',

    // Python Chapter 3 — explanations
    py_explain_9: 'Classes let you bundle data and behaviour together. Every class method receives self as the first argument, which refers to the specific instance.',

    // Python Chapter 3 — objectives (pipe-separated)
    py_obj_9: 'Understand what a class is|Use __init__ to set attributes|Create an object from a class',

    // Python Chapter 3 — pro tips
    py_tip_9: 'Use __repr__ to define how your object prints — it makes debugging much easier!',

    // ─── JavaScript Chapter 3 lesson titles ──────────────────────────────────
    js_array_methods: 'Array Methods',
    js_objects: 'Objects & Properties',
    js_closures: 'Closures & Scope',
    js_classes: 'Classes & OOP',
    js_error_handling: 'Error Handling',
    js_string_methods: 'String Methods',
    js_final_project: '🏆 JS Final Project',

    // JavaScript Chapter 3 — challenge descriptions
    js_challenge_9: 'Use the Array .map() method to double every number in an array.',
    js_challenge_10: 'Create an object literal with a brand property and log its value.',
    js_challenge_11: 'Build a closure-based counter that keeps its own internal state.',
    js_challenge_12: 'Create a class with a speak() method and call it on an instance.',
    js_challenge_13: 'Use try/catch to catch a ReferenceError and log a friendly message.',
    js_challenge_14: 'Use .toUpperCase() to transform a string and log the result.',
    js_challenge_15: 'Use Math.max() with spread syntax to find the highest score in an array.',

    // JavaScript Chapter 3 — hints
    js_hint_9: 'Use [1,2,3].map(n => n * 2) and console.log the result.',
    js_hint_10: 'Use const obj = { key: "value" }; then obj.key to access it.',
    js_hint_11: 'Return a function from inside another function — the inner function "closes over" count.',
    js_hint_12: 'class MyClass { method() { ... } } and then new MyClass().method()',
    js_hint_13: 'Wrap an invalid function call in try {} catch(e) {}',
    js_hint_14: '"some string".toUpperCase() returns a new uppercase string.',
    js_hint_15: 'Use Math.max(...scores) — the spread (...) unpacks the array into arguments.',

    // ─── Web Dev Chapter 3 lesson titles ─────────────────────────────────────
    web_forms: 'HTML Forms',
    web_css_variables: 'CSS Variables',
    web_animations: 'CSS Animations',
    web_semantic_html: 'Semantic HTML',
    web_media_queries: 'Media Queries',
    web_pseudo_selectors: 'Pseudo-Selectors',
    web_final_project: '🏆 Web Final Project',

    // Web Dev Chapter 3 — challenge descriptions
    web_challenge_9: 'Log an HTML <input> form element with type and placeholder attributes.',
    web_challenge_10: 'CSS Custom Properties (variables) help keep your styles consistent. Log a custom property.',
    web_challenge_11: 'CSS transitions make your UI feel alive. Log a transition shorthand rule.',
    web_challenge_12: 'Semantic HTML gives meaning to your structure. Log a <nav> element.',
    web_challenge_13: 'Media queries let you change styles based on screen size. Log a @media rule.',
    web_challenge_14: 'Pseudo-selectors target elements in special states. Log a :hover rule.',
    web_challenge_15: 'Final project: Assemble a complete HTML page skeleton and log it.',

    // Web Dev Chapter 3 — hints
    web_hint_9: 'Use single quotes inside the double-quoted string to avoid escaping issues.',
    web_hint_10: 'CSS variables start with -- and are declared inside :root {}.',
    web_hint_11: 'The shorthand is: transition: property duration timing-function;',
    web_hint_12: 'Use <nav>, <main>, <footer> instead of generic <div> tags.',
    web_hint_13: '@media (max-width: 600px) { ... } targets screens narrower than 600px.',
    web_hint_14: 'button:hover styles the button ONLY when the user hovers over it.',
    web_hint_15: 'Every HTML page starts with <html>, has a <head> and a <body>.',

    // ─── Chapter 4 section titles ────────────────────────────────────────────
    py_ch4_title: 'Advanced Python',
    js_ch4_title: 'Advanced JavaScript',
    web_ch4_title: 'Modern & Accessible Web',

    // ─── Python Chapter 4 lesson titles ──────────────────────────────────────
    python_generators: 'Generators',
    python_decorators: 'Decorators',
    python_file_io: 'File I/O',
    python_regex: 'Regular Expressions',
    python_testing: 'Unit Testing',
    python_master_project: '🥇 Python Master Project',

    // Python Chapter 4 — challenges
    py_challenge_16: 'Write a Python generator that lazily yields values one at a time.',
    py_challenge_17: 'Build a function decorator that runs code before the wrapped function.',
    py_challenge_18: 'Simulate reading and writing a file by storing and printing a string.',
    py_challenge_19: 'Use the re module to search for a pattern inside a string.',
    py_challenge_20: 'Write an assertion-based test to verify a simple calculation is correct.',
    py_challenge_21: 'Count word frequencies in a sentence and find the most repeated word.',

    // Python Chapter 4 — hints
    py_hint_16: 'Use yield inside a function to create a generator.',
    py_hint_17: 'A decorator is a function that takes a function and returns a new function.',
    py_hint_18: 'Store your content in a variable and print it instead of writing to disk.',
    py_hint_19: 'import re, then use re.search("pattern", text).group() to get the match.',
    py_hint_20: 'assert <expression> raises AssertionError if the expression is False.',
    py_hint_21: 'Use dict.get(word, 0) + 1 to count occurrences without a KeyError.',

    // ─── JavaScript Chapter 4 lesson titles ──────────────────────────────────
    js_destructuring: 'Destructuring',
    js_spread_rest: 'Spread & Rest',
    js_generators: 'Generators',
    js_regex: 'Regular Expressions',
    js_prototype: 'Prototype Chain',
    js_master_project: '🥇 JS Master Project',

    // JavaScript Chapter 4 — challenges
    js_challenge_16: 'Use object destructuring to extract a property from an object.',
    js_challenge_17: 'Use the spread operator (...) to merge two arrays and log the result length.',
    js_challenge_18: 'Create a generator function that yields "A" then "B" and log the first value.',
    js_challenge_19: 'Use a regex literal to test if a string contains a specific word.',
    js_challenge_20: 'Add a method to a constructor function\'s prototype and call it.',
    js_challenge_21: 'Find the most frequently occurring word in a string using a frequency map.',

    // JavaScript Chapter 4 — hints
    js_hint_16: 'const { name } = obj; extracts the name property directly.',
    js_hint_17: 'const merged = [...a, ...b]; creates a new flattened array.',
    js_hint_18: 'function* gen() { yield "A"; } — call gen().next().value for "A".',
    js_hint_19: '/pattern/.test(string) returns true or false.',
    js_hint_20: 'ConstructorFn.prototype.method = function() {...}',
    js_hint_21: 'Object.entries(freq).sort((a,b) => b[1]-a[1])[0][0] gets the top word.',

    // ─── Web Dev Chapter 4 lesson titles ─────────────────────────────────────
    web_css_grid_advanced: 'CSS Grid Areas',
    web_js_events: 'JS DOM Events',
    web_accessibility: 'Accessibility (a11y)',
    web_local_storage: 'Local Storage',
    web_performance: 'Web Performance',
    web_master_project: '🥇 Web Master Project',

    // Web Dev Chapter 4 — challenges
    web_challenge_16: 'Use CSS grid-template-areas to name grid regions for a page layout.',
    web_challenge_17: 'Simulate a DOM click event by logging "Button clicked!".',
    web_challenge_18: 'Add an alt attribute to an <img> tag to make it accessible.',
    web_challenge_19: 'Log the JS code to save a theme preference to localStorage.',
    web_challenge_20: 'Log a best-practice tip for improving web page loading performance.',
    web_challenge_21: 'Assemble a complete responsive page header with a nav inside.',

    // Web Dev Chapter 4 — hints
    web_hint_16: 'grid-template-areas uses quoted strings for each row.',
    web_hint_17: 'addEventListener("click", handler) — just log the event simulation.',
    web_hint_18: 'alt text describes the image for screen readers.',
    web_hint_19: 'localStorage.setItem("key", "value") saves data in the browser.',
    web_hint_20: 'loading="lazy" defers offscreen images until needed.',
    web_hint_21: "<header class='responsive-header'><nav>Menu</nav></header>",

    java_streams: 'Streams API',

    java_lambdas: 'Lambda Expressions',
    java_multithreading: 'Multithreading',
    sql_advanced_title: 'Advanced SQL',
    sql_subqueries: 'Subqueries',
    sql_transactions: 'Transactions',
    sql_indexing: 'Indexing',
    math_games: 'Math Games',
    math_games_desc: 'Have fun while learning Math!',
    math_addition: 'Addition',
    math_subtraction: 'Subtraction',
    math_puzzle: 'Math Puzzle',
    math_boss: 'Math Boss',
    math_challenge_1: 'What is 5 + 3?',
    math_challenge_2: 'What is 10 - 4?',
    math_challenge_3: 'What number comes next? 2, 4, 6, 8, ...',
    math_challenge_4: 'Solve this: (5 * 2) + 10',
    math_badge_adder: 'Top Adder',
    math_badge_sub: 'Subtractor',
    math_badge_puzzle: 'Puzzle Master',
    math_badge_calc: 'Calculator Champion',
    // Challenges
    py_challenge_1: 'Create a variable named "age" and set it to 10. Then print it!',
    py_challenge_2: 'Use a loop to print numbers 1, 2, and 3.',
    py_challenge_3: 'Quiz: How do you check if a number is even?',
    py_challenge_4: 'Create a function that says "Hello!".',
    py_challenge_5: 'Build a mini quiz game!',
    py_challenge_6: 'Create a list of fruits.',
    py_challenge_7: 'Create a user dictionary.',
    py_challenge_8: 'Quiz: What is the difference between a list and a tuple?',
    js_challenge_1: 'Print "Hello, JavaScript!" to the console.',
    js_challenge_2: 'Create a variable named "score" and print it.',
    js_challenge_3: 'Quiz: Which keyword is used for variables?',
    js_challenge_4: 'Create a function that says "Hi!".',
    js_challenge_5: 'Build an interactive story!',
    js_challenge_6: 'Create a simple Promise.',
    js_challenge_7: 'Use async/await to return a value.',
    js_challenge_8: 'Quiz: What does fetch() return?',
    web_challenge_1: 'Create your first HTML heading!',
    web_challenge_2: 'Add an image to your page.',
    web_challenge_3: 'Quiz: What does CSS stand for?',
    web_challenge_4: 'Use Flexbox to align items.',
    web_challenge_5: 'Build a page about your favorite animal!',
    web_challenge_6: 'Center items using Flexbox.',
    web_challenge_7: 'Create a 2-column grid.',
    web_challenge_8: 'Quiz: How do you make a site mobile-friendly?',
    bc_challenge_1: 'Move forward 3 times!',
    bc_explain_1: 'Sequences are steps that happen one after another. Just like a recipe, the computer reads your code from top to bottom.',
    bc_obj_1: 'Understand what a sequence is|Command the mascot to move|Reach the target safely',
    bc_tip_1: 'Always double-check your spelling! The computer only understands exact commands.',
    py_explain_1: 'Variables are like named boxes for storing data. You can put numbers or text in them to use later!',
    py_obj_1: 'Learn how to declare a variable|Assign a number to a variable|Print the variable to the console',
    py_tip_1: 'In Python, you do not need to use "let" or "const" like in other languages. Just write the name!',
    py_explain_2: 'Loops let you repeat actions without writing the same code over and over. A "for" loop repeats a specific number of times.',
    py_obj_2: 'Learn the "for" loop syntax|Understand the range() function|Print multiple numbers',
    py_tip_2: 'Remember that range(1, 4) stops BEFORE 4. So it only prints 1, 2, 3!',
    py_explain_3: 'Conditionals are how computers make decisions. If a condition is true, one thing happens. Else, something else happens.',
    py_obj_3: 'Use an "if" statement|Use an "else" statement|Compare numbers using >=',
    py_tip_3: 'Indentation (spaces at the start of the line) is super important in Python for blocks of code like "if" statements!',
    py_explain_4: 'Functions are reusable blocks of code. You define them once with "def", and can call them as many times as you want.',
    py_obj_4: 'Define a custom function|Use the "def" keyword|Call the function to run it',
    py_tip_4: 'Don\'t forget the parentheses () when defining or calling a function, even if it has no parameters.',
    py_explain_5: 'Lists are like a train with many cars. They let you hold many items in a single variable.',
    py_obj_5: 'Create a list of strings|Understand zero-based indexing|Print the first item of a list',
    py_tip_5: 'In programming, we start counting at 0! So the first item is at index [0], not [1].',
    js_explain_1: 'The console is a tool for developers to print messages. It helps you see what your code is doing behind the scenes.',
    js_obj_1: 'Find the console output window|Learn the console.log() command|Print a string of text',
    js_tip_1: 'Make sure to always wrap your text in quotation marks! \'Like this\' or "Like this".',
    js_explain_2: 'Variables are like containers for storing data values. In modern JavaScript, we use "let" to declare a variable that can change.',
    js_obj_2: 'Declare a variable using "let"|Assign a number value|Log the variable',
    js_tip_2: 'Don\'t forget the semicolon ; at the end of your statements!',
    js_explain_3: 'If/Else statements let your code make decisions based on whether a condition is true or false.',
    js_obj_3: 'Create an "if" block|Create an "else" block|Test a boolean condition',
    js_tip_3: 'Use curly braces { } to wrap the code that should run for the if/else blocks.',
    js_explain_4: 'Functions are blocks of code designed to perform a particular task. You can call them by name whenever you need them.',
    js_obj_4: 'Define a function using "function"|Write the function body|Execute the function',
    js_tip_4: 'A function doesn\'t run until you call it with parentheses, like this: myFunction()',
    js_explain_5: 'Arrays are special variables that can hold more than one value at a time, like a list.',
    js_obj_5: 'Create an array with square brackets []|Add strings to the array|Access the first element via index 0',
    js_tip_5: 'Arrays are zero-indexed, meaning the first item is accessed with [0], not [1]!',
    bc_challenge_2: 'Turn left and move forward.',
    bc_challenge_3: 'Navigate the path!',
    bc_challenge_4: 'Escape the maze!',
    bc_challenge_5: 'Quiz: What is a loop?',
    bc_challenge_6: 'Jump 5 times using a loop.',
    bc_challenge_7: 'Handle a click event.',
    bc_challenge_8: 'Quiz: What is an event?',
    bc_challenge_9: 'Use a condition to check a number.',
    bc_challenge_10: 'Store a value in a variable.',
    bc_challenge_11: 'Become a logic master!',
    bc_hint_1: 'Try writing console.log("forward") three times!',
    bc_hint_2: 'First log "left", then log "forward".',
    show_hint: 'Show Hint',
    hide_hint: 'Hide Hint',
    py_hint_1: 'Variables are like boxes. Use age = 10.',
    py_hint_2: 'Use range(1, 4) to get numbers 1, 2, and 3.',
    py_hint_3: 'Use indentation (4 spaces) after "if" and "else".',
    py_hint_4: 'Use "def" and then the function name, followed by ().',
    py_hint_5: 'Use square brackets [] to create a list.',
    js_hint_1: 'Type console.log("Hello, JavaScript!"); exactly.',
    js_hint_2: 'Use let score = 100; to create your variable.',
    js_hint_3: 'Use curly braces {} for the if and else blocks.',
    js_hint_4: 'Define with "function sayHi()" then call with "sayHi()".',
    js_hint_5: 'Use square brackets [] for arrays: let a = ["x", "y"]',
    web_hint_3: 'Try writing the CSS property name, a colon, then the value.',
    web_hint_4: 'Flexbox changes how elements are laid out inside a container.',
    web_hint_5: 'A <div> is a generic container element.',
    // Python Lesson 1 Quiz
    py_q1_q1: 'What is a variable in Python?',
    py_q1_o1a: 'A container that stores a data value',
    py_q1_o1b: 'A type of loop',
    py_q1_o1c: 'A function that runs automatically',
    py_q1_o1d: 'A special keyword that only Python has',
    py_q1_f1: 'Correct! A variable is a named container that holds a value, like a box with a label.',
    py_q1_q2: 'Which of the following correctly creates a variable named "score" with a value of 10?',
    py_q1_o2a: 'var score = 10',
    py_q1_o2b: 'let score = 10',
    py_q1_o2c: 'score = 10',
    py_q1_o2d: 'int score = 10',
    py_q1_f2: 'In Python, you simply write the variable name = value. No "var", "let", or "int" needed!',
    py_q1_q3: 'How do you display a variable\'s value in Python?',
    py_q1_o3a: 'display(age)',
    py_q1_o3b: 'print(age)',
    py_q1_o3c: 'console.log(age)',
    py_q1_o3d: 'echo age',
    py_q1_f3: 'In Python, we use print() to display values. console.log() is JavaScript!',
    // JavaScript Lesson 1 Quiz
    js_q1_q1: 'What does console.log() do in JavaScript?',
    js_q1_o1a: 'It saves data to a file',
    js_q1_o1b: 'It prints a message to the browser console',
    js_q1_o1c: 'It creates a pop-up alert',
    js_q1_o1d: 'It connects to a server',
    js_q1_f1: 'console.log() is the most common way to print/debug values in JavaScript. It shows output in the developer console.',
    js_q1_q2: 'Which symbol do you use to open the developer console in most browsers?',
    js_q1_o2a: 'F12',
    js_q1_o2b: 'Ctrl + C',
    js_q1_o2c: 'Alt + F4',
    js_q1_o2d: 'Ctrl + S',
    js_q1_f2: 'Pressing F12 (or Fn+F12 on some keyboards) opens the browser\'s DevTools, which includes the Console tab.',
    js_q1_q3: 'What surrounds a text string in JavaScript?',
    js_q1_o3a: 'Curly braces {}',
    js_q1_o3b: 'Square brackets []',
    js_q1_o3c: 'Parentheses ()',
    js_q1_o3d: 'Quotation marks " " or \' \'',
    js_q1_f3: 'Strings (text) must be surrounded by quotation marks, either double (") or single (\') quotes.',
    web_hint_1: 'Tags start with < and end with >. Try <h1>Hello World</h1>.',
    web_hint_2: 'Use single quotes for the string if the tag has double quotes: \'<img src="magic.png">\'.',
    cpp_challenge_1: 'Print "Hello C++!" to the console.',
    cpp_challenge_2: 'Use a pointer to access a variable.',
    cpp_challenge_3: 'Quiz: What is a class?',
    cpp_challenge_4: 'Use the STL vector.',
    cpp_challenge_5: 'Build a calculator!',
    java_challenge_1: 'Print "Hello Java" to the console.',
    java_challenge_2: 'Create your first Java class.',
    java_challenge_3: 'Quiz: What is an ArrayList?',
    java_challenge_4: 'Build a bank account system!',
    sql_challenge_1: 'Select all users from the database.',
    sql_challenge_2: 'Filter users by age.',
    sql_challenge_3: 'Quiz: What is a JOIN?',
    sql_challenge_4: 'Query a complex database!',
    ts_challenge_1: 'Define a variable with a specific type.',
    ts_challenge_2: 'Create an interface for a user.',
    ts_challenge_3: 'Quiz: What are Generics?',
    ts_challenge_4: 'Build a typed Todo list!',
    bc_mod_1_title: 'Foundations of Logic',
    bc_mod_1_desc: 'Master the basic building blocks of programming.',
    bc_lvl_1_title: 'Level 1: Sequences',
    bc_lvl_2_title: 'Level 2: Loops',
    bc_mod_2_title: 'Intermediate Concepts',
    bc_mod_2_desc: 'Take your coding skills to the next level with events and data.',
    bc_lvl_3_title: 'Level 3: Events',
  },
  fr: {
    path: '/fr',
    home: 'Accueil',
    learn: 'Apprendre',
    profile: 'Profil',
    creations: 'Créations',
    shop: 'Boutique',
    xp: 'XP',
    streak: 'Série',
    start: 'Commencer',
    locked: 'Verrouillé',
    completed: 'Terminé',
    lesson_complete: 'Leçon Terminée !',
    you_earned: 'Tu as gagné',
    continue: 'Continuer',
    exit: 'Quitter',
    login: 'Connexion',
    signUp: 'S\'inscrire',
    username: 'Nom d\'utilisateur',
    email: 'E-mail',
    password: 'Mot de passe',
    create_account: 'Créer un compte',
    or_continue_with: 'OU',
    continue_with_google: 'Continuer avec Google',
    logout: 'Déconnexion',
    welcome_back: 'Bon Retour !',
    join_the_adventure: 'Rejoins l\'aventure !',
    my_profile: 'Mon Profil',
    my_badges: 'Mes Badges',
    my_creations: 'Mes Créations',
    start_creating_prompt: 'Crée ton premier jeu pour le voir ici !',
    skip_for_now: 'Passer pour l\'instant',
    choose_your_path: 'Choisis Ton Aventure !',
    coming_soon: 'Bientôt Disponible',
    change_path: 'Changer de Voie',
    back: 'Retour',
    next: 'Suivant',
    search_lessons: 'Rechercher des leçons...',
    goals: 'Objectifs',
    leaderboard: 'Classement',
    store: 'Boutique',
    settings: 'Réglages',
    settings_language_desc: 'Choisissez la langue de l\'interface.',
    appearance: 'Apparence',
    light_mode: 'Mode Clair',
    dark_mode: 'Mode Sombre',
    stepper_learning_outcomes: 'Objectifs d\'apprentissage',
    upload_file_or_select_source: 'Télécharger un fichier ou sélectionner une source',
    drag_drop_file: 'Glissez-déposez un fichier ici',
    choose_a_file: 'Choisir un fichier',
    supported_file_types: 'Types supportés : PDF, DOCX, TXT',
    uploaded_files: 'Fichiers téléchargés',
    total_file_size: 'Taille totale',
    content_language: 'Langue du contenu',
    ai_creating_quiz: 'L\'IA crée votre quiz...',
    ai_warning: 'Cela peut prendre quelques secondes.',
    stepper_preview: 'Aperçu',
    challenge: 'Défi',
    run_code: 'Exécuter le code',
    language_english: 'Anglais',
    language_french: 'Français',
    language_arabic: 'Arabe',
    speaking_wizard_duration_title: 'Durée de la conversation',
    appearance_desc: 'Changez de mode pour le confort de vos yeux !',
    wip: '(En cours)',
    // Home Hub
    welcome_message: 'Prêt pour ta prochaine aventure ?',
    magic_found: "J'ai trouvé de la magie pour toi ! 🪄",
    day_streak: 'Série de Jours',
    total_xp_label: 'XP Total',
    learn_adventure_desc: 'Débloque de nouveaux mondes et maîtrise les sorts de code !',
    create_adventure_desc: 'Utilise tes pouvoirs pour construire des jeux !',
    did_you_know: 'Le savais-tu ?',
    code_fact: 'Le code est juste une liste d\'instructions pour ton ami robot !',
    // Brain Training
    brain_training: 'Entraînement Cérébral',
    brain_training_challenges: 'Défis',
    brain_training_workouts: 'Exercices',
    brain_training_desc: 'Entraîne ton esprit avec des défis amusants !',
    brain_training_play: 'Jouer',
    brain_training_back: 'Retour',
    brain_training_challenges_info: 'Les défis t\'aident à voir tes progrès et ton classement. Chaque test révèle ce que tu sais et ce qu\'il faut travailler.',
    brain_training_workouts_info: 'Les exercices cérébraux améliorent tes compétences. Explore toutes les catégories pour un progrès équilibré.',
    brain_training_next_level: 'Passe à la vitesse supérieure !',
    brain_training_unlock: 'Débloquer tout',
    brain_training_unlimited_access: 'Accès illimité à tous les défis',
    brain_training_unlimited_workouts: 'Entraîne-toi librement sans limites',
    brain_training_strengths: 'Vois tes forces et tes points à améliorer',
    brain_training_ai_tips: 'Obtiens des conseils intelligents de l\'IA',
    brain_training_new_puzzles: 'Défie-toi avec de nouveaux casse-têtes',
    brain_training_premium: 'Profite de toutes les fonctionnalités premium',
    brain_training_all_challenges: 'Tous les Défis',
    brain_training_free_tries: 'Essais gratuits restants',
    brain_training_questions: 'Questions',
    brain_training_previous: 'Précédent',
    brain_training_next_challenge: 'Défi Suivant',
    brain_training_finish: 'Terminer',
    brain_training_math: 'Maths',
    brain_training_logic: 'Logique',
    brain_training_problem_solving: 'Résolution de Problèmes',
    // Quiz Play
    perfect_score: 'Parfait !',
    well_done: 'Bien joué !',
    mission_accomplished: 'Mission Accomplie',
    questions_correct: 'Questions Correctes',
    return_to_hub: 'Retour à l\'Accueil',
    choose_magic_spell: 'Choisis le bon sort magique !',
    check_answer: 'Vérifier',
    amazing_feedback: 'Incroyable !',
    correct_answer_label: 'Bonne réponse :',
    keep_up_magic: 'Continue comme ça !',
    // Lesson Screen
    genius: 'GÉNIE !',
    mission_complete_msg: 'Tu as terminé la mission !',
    star_xp_units: 'XP ÉTOILE',
    next_adventure: 'Prochaine Aventure !',
    code_editor_title: 'Éditeur de Code',
    running: 'Exécution...',
    solution: 'Solution',
    use_this_code: 'Utiliser ce code',
    im_a_teacher: "Je suis un enseignant",
    im_a_student: "Je suis un étudiant",
    // Wizard
    last_details: 'Derniers Détails',
    questions_label: 'Questions',
    generate_magic: 'GÉNÉRER AVEC MAGIE',
    save_creation: 'SAUVEGARDER',
    consulting_ai: 'Consultation des Professeurs IA...',
    back_button: 'RETOUR',
    continue_button: 'CONTINUER',
    // Creations
    no_content_saved: 'Aucun contenu enregistré.',
    vault_empty: 'Ton coffre magique est vide.',
    start_creating_now: 'Crée quelque chose dans le Studio pour commencer !',
    view_all: 'Voir Tout',
    recent_contents: 'Contenus Récents',
    content_type: 'Type de Contenu',
    stage: 'Niveau',
    question_count: 'Nombre de Questions',
    language_label: 'Langue',
    view_learning_outcomes: 'Voir les Objectifs',
    assign: 'Assigner',
    open_content: 'Ouvrir',
    rename: 'Renommer',
    share: 'Partager',
    quiz: 'Quiz',
    multiple_choice: 'Choix multiple',
    // Profile
    following: 'Abonnements',
    followers: 'Abonnés',
    league_label: 'Ligue',
    no_bio: 'Pas encore de bio. Prêt pour l\'aventure !',
    unlocked_status: 'DÉBLOQUÉ',
    locked_status: 'VERROUILLÉ',
    edit_profile: 'Modifier le Profil',
    cancel: 'Annuler',
    save: 'Enregistrer',
    name_label: 'Nom',
    bio_label: 'Bio',
    // Others
    type_or_talk: 'Écris ou parle...',
    time_left: 'Temps restant',
    // Curriculum
    curriculum_moroccan: 'Programme National Marocain',
    curriculum_ib: 'Baccalauréat International (IB)',
    curriculum_us_core: 'Normes US Core',
    stage_preschool: 'Préscolaire (4-5 ans)',
    stage_primary: 'Primaire (6 ans)',
    stage_lower_secondary: 'Collège (3 ans)',
    stage_upper_secondary: 'Lycée (3 ans)',
    select_curriculum: 'Sélectionner le Programme',
    select_stage: 'Sélectionner le Niveau',
    stage_1: 'Niveau 1',
    stage_2: 'Niveau 2',
    stage_3: 'Niveau 3',
    stage_4: 'Niveau 4',
    stage_5: 'Niveau 5',
    stage_6: 'Niveau 6',
    // Game Studio
    game_studio: 'Studio de Jeux',
    game_studio_desc: 'Créez des jeux interactifs ou des devoirs avec l\'IA.',
    create: 'Créer',
    game_studio_import_title: 'Importer Votre Contenu',
    game_studio_import_desc: 'Créez facilement vos jeux avec l\'IA en utilisant n\'importe quel matériel.',
    game_studio_math_title: 'Maths',
    game_studio_math_desc: 'Jeux de maths conformes au programme avec l\'IA.',
    game_studio_science_title: 'Science',
    game_studio_science_desc: 'Jeux de science conformes au programme avec l\'IA.',
    game_studio_french_title: 'Français',
    game_studio_french_desc: 'Jeux de français conformes au programme avec l\'IA.',
    // Question Lab
    question_lab: 'Labo Questions',
    question_lab_desc: 'Générez des quiz et des devoirs avec l\'IA.',
    generate: 'Générer',
    question_lab_import_desc: 'Créez des questions d\'entraînement avec l\'IA.',
    question_lab_math_desc: 'Questions de maths conformes au programme.',
    question_lab_science_desc: 'Questions de sciences conformes au programme.',
    question_lab_french_desc: 'Questions de français conformes au programme.',
    // Smart Books
    smart_books: 'Livres Intelligents',
    smart_books_desc: 'Utilisez l\'IA pour créer votre livre ou lire dans votre langue.',
    smart_books_audiobooks_title: 'Écouter des Livres Audio',
    smart_books_audiobooks_desc: 'Découvrez de nouvelles histoires et stimulez votre imagination.',
    smart_books_create_title: 'Créer Votre Propre Livre',
    smart_books_create_desc: 'Rédigez, illustrez et publiez vos propres histoires magiques avec l\'IA.',
    open: 'Ouvrir',
    // Scientific Inquiry
    scientific_inquiry: 'Enquête Scientifique',
    scientific_inquiry_desc: 'Explorez les merveilles de la science avec des expériences interactives.',
    speaking_hub: 'Hub de Parole',
    speaking_hub_desc: 'Entraînez-vous à parler une langue étrangère avec l\'IA.',
    start_speaking: 'Commencer',
    speaking_wizard_level: 'Niveau',
    speaking_wizard_age: 'Âge',
    speaking_wizard_subject: 'Sujet',
    speaking_wizard_duration: 'Durée',
    speaking_wizard_duration_mins: 'min',
    speaking_wizard_topic_title: 'Sujet',
    speaking_hub_english_american: 'Anglais (Américain)',
    speaking_hub_english_british: 'Anglais (Britannique)',
    speaking_hub_french: 'Français',
    speaking_hub_arabic: 'Arabe',
    // ... paths ...
    // Paths
    paths: 'Parcours',
    block_coding: 'Code en Blocs',
    block_coding_desc: 'Commencez avec des blocs colorés !',
    sequences: 'Séquences',
    loops: 'Boucles',
    events: 'Événements',
    maze_game: 'Labyrinthe',
    logic: 'Logique',
    conditionals: 'Conditions',
    variables: 'Variables',
    logic_master: 'Maître de la Logique',
    python: 'Python',
    python_desc: 'Plongez dans le code avec Python.',
    javascript: 'JavaScript',
    javascript_desc: 'Créez des sites avec le langage du web.',
    lua: 'Lua',
    lua_desc: 'Créez des jeux puissants avec Lua.',
    web_dev: 'Web Dev',
    web_dev_desc: 'Construisez vos sites avec HTML et CSS.',
    python_data_structures: 'Structures de Données',
    python_lists: 'Listes',
    python_dicts: 'Dictionnaires',
    python_tuples: 'Tuples',
    js_async_title: 'JS Asynchrone',
    js_promises: 'Promesses',
    js_async_await: 'Async/Await',
    js_fetch_api: 'API Fetch',
    web_advanced_title: 'Mises en Page Avancées',
    web_flexbox: 'Flexbox',
    web_grid: 'Grille CSS',
    web_responsive_design: 'Design Responsif',
    cpp_advanced_title: 'C++ Avancé',
    cpp_templates: 'Templates',
    cpp_memory: 'Gestion de la Mémoire',
    cpp_quiz_adv: 'Quiz Avancé',
    java_advanced_title: 'Java Avancé',
    java_streams: 'API Streams',
    java_lambdas: 'Expressions Lambda',
    java_multithreading: 'Multithreading',
    sql_advanced_title: 'SQL Avancé',
    sql_subqueries: 'Sous-requêtes',
    sql_transactions: 'Transactions',
    sql_indexing: 'Indexation',
    math_games: 'Jeux de Maths',
    math_games_desc: 'Amuse-toi en apprenant les maths !',
    math_addition: 'Addition',
    math_subtraction: 'Soustraction',
    math_puzzle: 'Casse-tête',
    math_boss: 'Boss des Maths',
    math_challenge_1: 'Combien font 5 + 3 ?',
    math_challenge_2: 'Combien font 10 - 4 ?',
    math_challenge_3: 'Quel nombre suit ? 2, 4, 6, 8, ...',
    math_challenge_4: 'Résous ceci : (5 * 2) + 10',
    math_badge_adder: 'As de l\'Addition',
    math_badge_sub: 'As de la Soustraction',
    math_badge_puzzle: 'Maître des Puzzles',
    math_badge_calc: 'Champion de la Calculette',
    // Challenges
    py_challenge_1: 'Créez une variable nommée "age" et réglez-la sur 10. Puis affichez-la !',
    py_challenge_2: 'Utilisez une boucle pour afficher les nombres 1, 2 et 3.',
    py_challenge_3: 'Quiz : Comment vérifier si un nombre est pair ?',
    py_challenge_4: 'Créez une fonction qui dit "Bonjour !".',
    py_challenge_5: 'Construisez un mini jeu de quiz !',
    py_challenge_6: 'Créez une liste de fruits.',
    py_challenge_7: 'Créez un dictionnaire utilisateur.',
    py_challenge_8: 'Quiz : Quelle est la différence entre une liste et un tuple ?',
    js_challenge_1: 'Affichez "Hello, JavaScript!" dans la console.',
    js_challenge_2: 'Créez une variable nommée "score" et affichez-la.',
    js_challenge_3: 'Quiz : Quel mot-clé est utilisé pour les variables ?',
    js_challenge_4: 'Créez une fonction qui dit "Salut !".',
    js_challenge_5: 'Construisez une histoire interactive !',
    js_challenge_6: 'Créez une Promise simple.',
    js_challenge_7: 'Utilisez async/await pour retourner une valeur.',
    js_challenge_8: 'Quiz : Que retourne fetch() ?',
    web_challenge_1: 'Créez votre premier titre HTML !',
    web_challenge_2: 'Ajoutez une image à votre page.',
    web_challenge_3: 'Quiz : Que signifie CSS ?',
    web_challenge_4: 'Utilisez Flexbox pour aligner les éléments.',
    web_challenge_5: 'Construisez une page sur votre animal préféré !',
    web_challenge_6: 'Centrez les éléments avec Flexbox.',
    web_challenge_7: 'Créez une grille à 2 colonnes.',
    web_challenge_8: 'Quiz : Comment rendre un site adapté aux mobiles ?',
    bc_challenge_1: 'Avancez 3 fois !',
    bc_explain_1: 'Les séquences sont des étapes qui se succèdent. Comme une recette, l\'ordinateur lit votre code de haut en bas.',
    bc_obj_1: 'Comprendre ce qu\'est une séquence|Commander à la mascotte d\'avancer|Atteindre la cible',
    bc_tip_1: 'Vérifiez toujours votre orthographe ! L\'ordinateur ne comprend que les commandes exactes.',
    py_explain_1: 'Les variables sont comme des boîtes nommées pour stocker des données. Vous pouvez y mettre des chiffres ou du texte !',
    py_obj_1: 'Apprendre à déclarer une variable|Associer un nombre à la variable|Imprimer la variable',
    py_tip_1: 'En Python, vous n\'avez pas besoin d\'utiliser "let" ou "const".',
    py_explain_2: 'Les boucles permettent de répéter des actions. Une boucle "for" se répète un nombre spécifique de fois.',
    py_obj_2: 'Apprendre la syntaxe de la boucle "for"|Comprendre la fonction range()|Imprimer plusieurs nombres',
    py_tip_2: 'N\'oubliez pas que range(1, 4) s\'arrête AVANT 4. Ça n\'imprime que 1, 2, 3 !',
    py_explain_3: 'Les conditions permettent aux ordinateurs de prendre des décisions (Si... Sinon...).',
    py_obj_3: 'Utiliser une instruction "if"|Utiliser "else"|Comparer des nombres',
    py_tip_3: 'L\'indentation (les espaces) est super importante en Python pour les blocs de code !',
    py_explain_4: 'Les fonctions sont des blocs de code réutilisables créés avec "def".',
    py_obj_4: 'Définir une fonction|Utiliser le mot-clé "def"|Appeler la fonction',
    py_tip_4: 'N\'oubliez pas les parenthèses () lors de l\'appel d\'une fonction.',
    py_explain_5: 'Les listes permettent de conserver plusieurs éléments dans une seule variable.',
    py_obj_5: 'Créer une liste|Comprendre l\'indexation à partir de zéro|Imprimer le premier élément',
    py_tip_5: 'En programmation, on commence à compter à 0 ! Le premier élément est donc à l\'index [0].',
    js_explain_1: 'La console est un outil qui aide à voir ce que votre code fait en coulisses.',
    js_obj_1: 'Trouver la fenêtre du console|Apprendre la commande console.log()|Imprimer un morceau de texte',
    js_tip_1: 'N\'oubliez pas de mettre des guillemets autour de votre texte !',
    js_explain_2: 'Les variables sont des conteneurs pour stocker des valeurs. On utilise "let" pour une variable qui peut changer.',
    js_obj_2: 'Déclarer une variable avec "let"|Associer une valeur numérique|Imprimer la variable',
    js_tip_2: 'N\'oubliez pas le point-virgule ; à la fin de vos instructions !',
    js_explain_3: 'Les instructions If/Else permettent à votre code de prendre des décisions.',
    js_obj_3: 'Créer un bloc "if"|Créer un bloc "else"|Tester une condition',
    js_tip_3: 'Utilisez des accolades { } pour encapsuler le code des blocs if/else.',
    js_explain_4: 'Les fonctions sont des blocs de code conçus pour une tâche particulière.',
    js_obj_4: 'Définir une fonction|Écrire le corps de la fonction|Appeler la fonction',
    js_tip_4: 'Une fonction ne s\'exécute pas tant que vous ne l\'appelez pas : maFonction()',
    js_explain_5: 'Les tableaux (arrays) sont des variables spéciales pouvant contenir plusieurs valeurs à la fois.',
    js_obj_5: 'Créer un tableau avec []|Ajouter des chaînes|Accéder au premier élément (index 0)',
    js_tip_5: 'Les tableaux commencent à 0 ! Le premier élément est donc accessible avec [0].',
    bc_challenge_2: 'Tournez à gauche et avancez.',
    bc_challenge_3: 'Naviguez sur le chemin !',
    bc_challenge_4: 'Échappez-vous du labyrinthe !',
    bc_challenge_5: 'Quiz : Qu\'est-ce qu\'une boucle ?',
    bc_challenge_6: 'Sautez 5 fois en utilisant une boucle.',
    bc_challenge_7: 'Gérez un événement de clic.',
    bc_challenge_8: 'Quiz : Qu\'est-ce qu\'un événement ?',
    bc_challenge_9: 'Utilisez une condition pour vérifier un nombre.',
    bc_challenge_10: 'Stockez une valeur dans une variable.',
    bc_challenge_11: 'Devenez un maître de la logique !',
    bc_hint_1: 'Essayez d\'écrire console.log("forward") trois fois !',
    bc_hint_2: 'Affichez d\'abord "left", puis "forward".',
    show_hint: 'Afficher l\'indice',
    hide_hint: 'Masquer l\'indice',
    py_hint_1: 'Les variables sont comme des boîtes. Utilisez age = 10.',
    py_hint_2: 'Utilisez range(1, 4) pour obtenir les nombres 1, 2 et 3.',
    py_hint_3: 'Utilisez l\'indentation (4 espaces) après "if" et "else".',
    py_hint_4: 'Utilisez "def" puis le nom de la fonction, suivi de ().',
    js_hint_1: 'Tapez console.log("Hello, JavaScript!"); exactement.',
    js_hint_2: 'Utilisez let score = 100; pour créer votre variable.',
    // Python Lesson 1 Quiz (FR)
    py_q1_q1: 'Qu\'est-ce qu\'une variable en Python ?',
    py_q1_o1a: 'Un conteneur qui stocke une valeur',
    py_q1_o1b: 'Un type de boucle',
    py_q1_o1c: 'Une fonction qui s\'exécute automatiquement',
    py_q1_o1d: 'Un mot-clé spécial propre à Python',
    py_q1_f1: 'Une variable est un conteneur nommé qui contient une valeur, comme une boîte étiquetée.',
    py_q1_q2: 'Laquelle crée correctement une variable "score" à 10 ?',
    py_q1_o2a: 'var score = 10',
    py_q1_o2b: 'let score = 10',
    py_q1_o2c: 'score = 10',
    py_q1_o2d: 'int score = 10',
    py_q1_f2: 'En Python, écrivez simplement nom = valeur. Pas besoin de "var", "let" ou "int" !',
    py_q1_q3: 'Comment afficher la valeur d\'une variable en Python ?',
    py_q1_o3a: 'display(age)',
    py_q1_o3b: 'print(age)',
    py_q1_o3c: 'console.log(age)',
    py_q1_o3d: 'echo age',
    py_q1_f3: 'En Python, on utilise print() pour afficher des valeurs.',
    // JavaScript Lesson 1 Quiz (FR)
    js_q1_q1: 'Que fait console.log() en JavaScript ?',
    js_q1_o1a: 'Il enregistre des données dans un fichier',
    js_q1_o1b: 'Il affiche un message dans la console du navigateur',
    js_q1_o1c: 'Il crée une alerte pop-up',
    js_q1_o1d: 'Il se connecte à un serveur',
    js_q1_f1: 'console.log() est la façon la plus courante d\'afficher des valeurs en JavaScript.',
    js_q1_q2: 'Quel raccourci ouvre la console du développeur ?',
    js_q1_o2a: 'F12',
    js_q1_o2b: 'Ctrl + C',
    js_q1_o2c: 'Alt + F4',
    js_q1_o2d: 'Ctrl + S',
    js_q1_f2: 'F12 ouvre les DevTools du navigateur, qui contiennent l\'onglet Console.',
    js_q1_q3: 'Qu\'est-ce qui entoure une chaîne de texte en JavaScript ?',
    js_q1_o3a: 'Accolades {}',
    js_q1_o3b: 'Crochets []',
    js_q1_o3c: 'Parenthèses ()',
    js_q1_o3d: 'Guillemets " " ou \' \'',
    js_q1_f3: 'Les chaînes de texte doivent être entourées de guillemets (" ou \').',
    web_hint_1: 'Les balises commencent par < et se terminent par >. Essayez <h1>Hello World</h1>.',
    web_hint_2: 'Utilisez des guillemets simples pour la chaîne si la balise a des guillemets doubles : \'<img src="magic.png">\'.',
    cpp_challenge_1: 'Affichez "Hello C++!" dans la console.',
    cpp_challenge_2: 'Utilisez un pointeur pour accéder à une variable.',
    cpp_challenge_3: 'Quiz : Qu\'est-ce qu\'une classe ?',
    cpp_challenge_4: 'Utilisez le vecteur STL.',
    cpp_challenge_5: 'Construisez une calculatrice !',
    java_challenge_1: 'Affichez "Hello Java" dans la console.',
    java_challenge_2: 'Créez votre première classe Java.',
    java_challenge_3: 'Quiz : Qu\'est-ce qu\'une ArrayList ?',
    java_challenge_4: 'Construisez un système de compte bancaire !',
    sql_challenge_1: 'Sélectionnez tous les utilisateurs de la base de données.',
    sql_challenge_2: 'Filtrez les utilisateurs par âge.',
    sql_challenge_3: 'Quiz : Qu\'est-ce qu\'une JOIN ?',
    sql_challenge_4: 'Interrogez une base de données complexe !',
    ts_challenge_1: 'Définissez une variable avec un type spécifique.',
    ts_challenge_2: 'Créez une interface pour un utilisateur.',
    ts_challenge_3: 'Quiz : Que sont les Generics ?',
    ts_challenge_4: 'Construisez une liste de tâches typée !',
    bc_mod_1_title: 'Bases de la Logique',
    bc_mod_1_desc: 'Maîtrisez les blocs de base de la programmation.',
    bc_lvl_1_title: 'Niveau 1 : Séquences',
    bc_lvl_2_title: 'Niveau 2 : Boucles',
    bc_mod_2_title: 'Concepts Intermédiaires',
    bc_mod_2_desc: 'Passez au niveau supérieur avec les événements et les données.',
    bc_lvl_3_title: 'Niveau 3 : Événements',
  },
  ar: {
    path: '/ar',
    home: 'الدار',
    learn: 'تعلم',
    profile: 'البروفيل',
    creations: 'داكشي اللي صاوبتي',
    shop: 'الحانوت',
    xp: 'نقطة',
    streak: 'السلسلة',
    start: 'بدا',
    locked: 'مسدود',
    completed: 'كملتي',
    lesson_complete: 'كملتي الدرس!',
    you_earned: 'ربحتي',
    continue: 'كمل',
    exit: 'خرج',
    login: 'دخل',
    signUp: 'صاوب حساب',
    username: 'سمية المستخدم',
    email: 'الإيميل',
    password: 'الكود',
    create_account: 'صاوب حساب',
    or_continue_with: 'ولا',
    continue_with_google: 'كمل بجوجل',
    logout: 'خرج',
    welcome_back: 'على سلامتك!',
    join_the_adventure: 'دخل للمغامرة!',
    my_profile: 'البروفيل ديالي',
    my_badges: 'الأوسمة ديالي',
    my_creations: 'داكشي اللي صاوبتي',
    start_creating_prompt: 'صاوب أول لعبة ديالك باش تبان هنا!',
    skip_for_now: 'دوز دابا',
    choose_your_path: 'ختار الطريق ديالك!',
    coming_soon: 'قريب',
    change_path: 'بدل الطريق',
    back: 'رجع',
    next: 'الجاي',
    search_lessons: 'قلب على الدروس...',
    goals: 'الأهداف',
    leaderboard: 'الترتيب',
    store: 'الحانوت',
    settings: 'الإعدادات',
    settings_language_desc: 'ختار اللغة ديال التطبيق.',
    appearance: 'الشكل',
    light_mode: 'الضو',
    dark_mode: 'الظلام',
    stepper_learning_outcomes: 'شنو غاتعلم',
    upload_file_or_select_source: 'طلع ملف ولا ختار منين',
    drag_drop_file: 'جر وحط الملف هنا',
    choose_a_file: 'ختار ملف',
    supported_file_types: 'الأنواع اللي خدامة: PDF, DOCX, TXT',
    uploaded_files: 'الملفات اللي طلعتي',
    total_file_size: 'الحجم كامل',
    content_language: 'اللغة ديال المحتوى',
    ai_creating_quiz: 'الذكاء الاصطناعي كيصاوب ليك الاختبار...',
    ai_warning: 'هادشي غاياخد شوية ديال الوقت.',
    stepper_preview: 'شوف قبل',
    challenge: 'تحدي',
    run_code: 'خدم الكود',
    language_english: 'الإنجليزية',
    language_french: 'الفرنسية',
    language_arabic: 'الدارجة',
    speaking_wizard_duration_title: 'شحال غاتهضر',
    appearance_desc: 'بدل بين الضو والظلام باش ترتاح عينيك!',
    wip: '(خدامين عليه)',
    // Home Hub
    welcome_message: 'واجد للمغامرة الجاية؟',
    magic_found: 'لقيت ليك شوية ديال السحر! 🪄',
    day_streak: 'السلسلة ديال الأيام',
    total_xp_label: 'مجموع النقط',
    learn_adventure_desc: 'حل عوالم جديدة وتعلم سحر الكود!',
    create_adventure_desc: 'استعمل القوة ديالك باش تصاوب ألعاب وقصص!',
    did_you_know: 'واش كتعرف؟',
    code_fact: 'الكود هو غير واحد الليستة ديال الأوامر للصديق ديالك الروبوت!',
    // Brain Training
    brain_training: 'تدريب الدماغ',
    brain_training_challenges: 'التحديات',
    brain_training_workouts: 'التمارين',
    brain_training_desc: 'درب عقلك بتحديات ممتعة!',
    brain_training_play: 'لعب',
    brain_training_back: 'رجع',
    brain_training_challenges_info: 'التحديات كتعاونك تشوف التقدم ديالك والترتيب. كل اختبار كيبين ليك شنو عرفتي وشنو خاصك تخدم عليه.',
    brain_training_workouts_info: 'تمارين الدماغ كتحسن المهارات ديالك. استكشف كاع الفئات باش تتقدم بشكل متوازن.',
    brain_training_next_level: 'ارتقي بتدريب الدماغ ديالك للمستوى الجاي!',
    brain_training_unlock: 'حل كاع الميزات',
    brain_training_unlimited_access: 'وصول بلا حدود لكاع التحديات',
    brain_training_unlimited_workouts: 'تدرب بحرية بلا حدود',
    brain_training_strengths: 'شوف نقاط القوة ديالك والمجالات اللي خاصك تحسن فيها',
    brain_training_ai_tips: 'حصل على نصائح ذكية من الذكاء الاصطناعي',
    brain_training_new_puzzles: 'تحدى راسك بألغاز جديدة',
    brain_training_premium: 'استمتع بكاع الميزات المتقدمة',
    brain_training_all_challenges: 'كاع التحديات',
    brain_training_free_tries: 'المحاولات المجانية اللي بقات',
    brain_training_questions: 'الأسئلة',
    brain_training_previous: 'السابق',
    brain_training_next_challenge: 'التحدي الجاي',
    brain_training_finish: 'سالي',
    brain_training_math: 'رياضيات',
    brain_training_logic: 'منطق',
    brain_training_problem_solving: 'حل المشاكل',
    // Quiz Play
    perfect_score: 'واعر!',
    well_done: 'تبارك الله عليك!',
    mission_accomplished: 'المهمة كملات',
    questions_correct: 'أسئلة صحيحة',
    return_to_hub: 'رجع للدار',
    choose_magic_spell: 'ختار السحر الصحيح!',
    check_answer: 'شوف',
    amazing_feedback: 'خطير!',
    correct_answer_label: 'الجواب الصحيح:',
    keep_up_magic: 'كمل السحر ديالك!',
    // Lesson Screen
    genius: 'عبقري!',
    mission_complete_msg: 'كملتي المهمة!',
    star_xp_units: 'نقطة سحرية',
    next_adventure: 'المغامرة الجاية!',
    code_editor_title: 'بلاصة الكود',
    running: 'خدام...',
    solution: 'الحل',
    use_this_code: 'استعمل هاد الكود',
    im_a_teacher: "أنا أستاذ",
    im_a_student: "أنا تلميذ",
    // Wizard
    last_details: 'آخر التفاصيل',
    questions_label: 'أسئلة',
    generate_magic: 'صاوب بالسحر',
    save_creation: 'حفظ داكشي اللي صاوبتي',
    consulting_ai: 'كنسولو المعلمين ديال الذكاء الاصطناعي...',
    back_button: 'رجع',
    continue_button: 'كمل',
    // Creations
    no_content_saved: 'باقي ما حفظتي والو.',
    vault_empty: 'الخزنة السحرية ديالك خاوية.',
    start_creating_now: 'صاوب شي حاجة في ستوديو الألعاب باش تبدا!',
    view_all: 'شوف كلشي',
    recent_contents: 'آخر داكشي اللي صاوبتي',
    content_type: 'نوع المحتوى',
    stage: 'المرحلة',
    question_count: 'عدد الأسئلة',
    language_label: 'اللغة',
    view_learning_outcomes: 'شوف شنو غاتعلم',
    assign: 'عطي',
    open_content: 'حل',
    rename: 'بدل السمية',
    share: 'بارطاجي',
    quiz: 'اختبار',
    multiple_choice: 'متعدد الخيارات',
    // Profile
    following: 'متابعة',
    followers: 'متابعين',
    league_label: 'الدوري',
    no_bio: 'باقي ما كاين وصف. واجد للمغامرة!',
    unlocked_status: 'محلول',
    locked_status: 'مسدود',
    edit_profile: 'بدل البروفيل',
    cancel: 'حبس',
    save: 'حفظ',
    name_label: 'السمية',
    bio_label: 'الوصف',
    // Others
    type_or_talk: 'اكتب ولا هضر...',
    time_left: 'الوقت اللي بقى',
    // Curriculum
    curriculum_moroccan: 'المنهاج الوطني المغربي',
    curriculum_ib: 'البكالوريا الدولية (IB)',
    curriculum_us_core: 'المعايير الأمريكية',
    stage_preschool: 'التعليم الأولي (4-5 سنوات)',
    stage_primary: 'التعليم الابتدائي (6 سنوات)',
    stage_lower_secondary: 'التعليم الإعدادي (3 سنوات)',
    stage_upper_secondary: 'التعليم الثانوي (3 سنوات)',
    select_curriculum: 'ختار المنهاج',
    select_stage: 'ختار المرحلة',
    stage_1: 'المرحلة 1',
    stage_2: 'المرحلة 2',
    stage_3: 'المرحلة 3',
    stage_4: 'المرحلة 4',
    stage_5: 'المرحلة 5',
    stage_6: 'المرحلة 6',
    // Game Studio
    game_studio: 'ستوديو الألعاب',
    game_studio_desc: 'صاوب ألعاب تفاعلية ولا واجبات بالذكاء الاصطناعي.',
    create: 'صاوب',
    game_studio_import_title: 'جيب المحتوى ديالك',
    game_studio_import_desc: 'صاوب ألعابك بسهولة بأي حاجة عندك.',
    game_studio_math_title: 'رياضيات',
    game_studio_math_desc: 'ألعاب رياضيات على حساب المنهاج.',
    game_studio_science_title: 'علوم',
    game_studio_science_desc: 'ألعاب علوم على حساب المنهاج.',
    game_studio_french_title: 'فرنسية',
    game_studio_french_desc: 'ألعاب فرنسية على حساب المنهاج.',
    // Question Lab
    question_lab: 'مختبر الأسئلة',
    question_lab_desc: 'صاوب اختبارات وواجبات بالذكاء الاصطناعي.',
    generate: 'صاوب',
    question_lab_import_desc: 'صاوب أسئلة تدريبية بسهولة.',
    question_lab_math_desc: 'أسئلة رياضيات على حساب المنهاج.',
    question_lab_science_desc: 'أسئلة علوم على حساب المنهاج.',
    question_lab_french_desc: 'أسئلة فرنسية على حساب المنهاج.',
    // Smart Books
    smart_books: 'الكتب الذكية',
    smart_books_desc: 'استخدم الذكاء الاصطناعي لكتابة كتابك أو قراءة كتب بلغتك.',
    smart_books_audiobooks_title: 'استمع إلى الكتب الصوتية',
    smart_books_audiobooks_desc: 'اكتشف قصصًا جديدة وأشعل خيالك على طول الطريق.',
    smart_books_create_title: 'اصنع كتابك الخاص',
    smart_books_create_desc: 'اكتب، ارسم، وانشر قصصك السحرية باستخدام الذكاء الاصطناعي.',
    open: 'حل',
    // Scientific Inquiry
    scientific_inquiry: 'البحث العلمي',
    scientific_inquiry_desc: 'اكتشف عجائب العلوم من خلال تجارب تفاعلية.',
    speaking_hub: 'مركز الهضرة',
    speaking_hub_desc: 'تدرب على الهضرة بلغة أجنبية مع الذكاء الاصطناعي.',
    start_speaking: 'بدا',
    speaking_wizard_level: 'المستوى',
    speaking_wizard_age: 'العمر',
    speaking_wizard_subject: 'الموضوع',
    speaking_wizard_duration: 'المدة',
    speaking_wizard_duration_mins: 'دقائق',
    speaking_wizard_topic_title: 'الموضوع',
    speaking_hub_english_american: 'الإنجليزية (الأمريكية)',
    speaking_hub_english_british: 'الإنجليزية (البريطانية)',
    speaking_hub_french: 'الفرنسية',
    speaking_hub_arabic: 'العربية',
    // ... paths ...
    // Paths
    paths: 'الطرق',
    block_coding: 'البرمجة بالبلوكات',
    block_coding_desc: 'بدا ببلوكات ملونة وزوينة!',
    sequences: 'التسلسلات',
    loops: 'الحلقات',
    events: 'الأحداث',
    maze_game: 'المتاهة',
    logic: 'المنطق',
    conditionals: 'الشروط',
    variables: 'المتغيرات',
    logic_master: 'سيد المنطق',
    python: 'بايثون',
    python_desc: 'تعلم البرمجة الحقيقية ببايثون.',
    javascript: 'جافاسكريبت',
    javascript_desc: 'صاوب مواقع الويب بجافاسكريبت.',
    lua: 'لوا',
    lua_desc: 'صاوب ألعاب قوية بلوا.',
    web_dev: 'تطوير الويب',
    web_dev_desc: 'صاوب مواقعك بـ HTML و CSS.',
    python_data_structures: 'هياكل البيانات',
    python_lists: 'الليستات',
    python_dicts: 'القواميس',
    python_tuples: 'الصفوف',
    js_async_title: 'جافاسكريبت غير المتزامنة',
    js_promises: 'الوعود',
    js_async_await: 'Async/Await',
    js_fetch_api: 'Fetch API',
    web_advanced_title: 'تخطيطات متقدمة',
    web_flexbox: 'Flexbox',
    web_grid: 'CSS Grid',
    web_responsive_design: 'التصميم المتجاوب',
    cpp_advanced_title: 'C++ متقدم',
    cpp_templates: 'القوالب',
    cpp_memory: 'إدارة الذاكرة',
    cpp_quiz_adv: 'اختبار متقدم',
    java_advanced_title: 'جافا متقدم',
    java_streams: 'Streams API',
    java_lambdas: 'تعبيرات لامبدا',
    java_multithreading: 'تعدد الخيوط',
    sql_advanced_title: 'SQL متقدم',
    sql_subqueries: 'الاستعلامات الفرعية',
    sql_transactions: 'المعاملات',
    sql_indexing: 'الفهرسة',
    math_games: 'ألعاب الرياضيات',
    math_games_desc: 'استمتع وتعلم الرياضيات في نفس الوقت!',
    math_addition: 'الجمع',
    math_subtraction: 'الطرح',
    math_puzzle: 'لغز الرياضيات',
    math_boss: 'زعيم الرياضيات',
    math_challenge_1: 'شحال هي 5 + 3؟',
    math_challenge_2: 'شحال هي 10 - 4؟',
    math_challenge_3: 'أشنو الرقم اللي جاي؟ 2، 4، 6، 8، ...',
    math_challenge_4: 'حل هادي: (5 * 2) + 10',
    math_badge_adder: 'بطل الجمع',
    math_badge_sub: 'بطل الطرح',
    math_badge_puzzle: 'معلم الألغاز',
    math_badge_calc: 'بطل الحسابات',
    // Challenges
    py_challenge_1: 'صاوب متغير سميتو "age" ودير فيه 10. ومن بعد طبعو!',
    py_challenge_2: 'استعمل حلقة باش تطبع الأرقام 1 و 2 و 3.',
    py_challenge_3: 'اختبار: كيفاش كتعرف واش الرقم زوجي؟',
    py_challenge_4: 'صاوب دالة كتقول "السلام!".',
    py_challenge_5: 'صاوب لعبة اختبار صغيرة!',
    py_challenge_6: 'صاوب ليستة ديال الفواكه.',
    py_challenge_7: 'صاوب قاموس ديال المستخدم.',
    py_challenge_8: 'اختبار: شنو الفرق بين الليستة والـ tuple؟',
    js_challenge_1: 'اطبع "Hello, JavaScript!" في الكونسول.',
    js_challenge_2: 'صاوب متغير سميتو "score" وطبعو.',
    js_challenge_3: 'اختبار: شنو هي الكلمة اللي كنستعملو للمتغيرات؟',
    js_challenge_4: 'صاوب دالة كتقول "السلام!".',
    js_challenge_5: 'صاوب قصة تفاعلية!',
    js_challenge_6: 'صاوب Promise بسيط.',
    js_challenge_7: 'استعمل async/await باش ترجع شي قيمة.',
    js_challenge_8: 'اختبار: شنو كترجع fetch()؟',
    web_challenge_1: 'صاوب أول عنوان HTML ديالك!',
    web_challenge_2: 'زيد تصويرة في الصفحة ديالك.',
    web_challenge_3: 'اختبار: شنو كتعني CSS؟',
    web_challenge_4: 'استعمل Flexbox باش تقاد العناصر.',
    web_challenge_5: 'صاوب صفحة على الحيوان المفضل ديالك!',
    web_challenge_6: 'وسط العناصر باستعمال Flexbox.',
    web_challenge_7: 'صاوب شبكة فيها 2 ديال الأعمدة.',
    web_challenge_8: 'اختبار: كيفاش كتخلي الموقع يخدم مزيان في التيليفون؟',
    bc_challenge_1: 'زيد القدام 3 ديال المرات!',
    bc_explain_1: 'التسلسلات هي خطوات كتمشي وحدة مورا وحدة. بحال شي وصفة، البيسي كيقرا الكود ديالك من الفوق لتحت.',
    bc_obj_1: 'نفهمو شنو هو التسلسل|نأمرو الشخصية تزيد للقدام|نوصلو للهدف',
    bc_tip_1: 'تأكد ديما من الكلمات كيفاش مكتوبة، حيت البيسي كيفهم غير الأوامر المضبوطة.',
    py_explain_1: 'المتغيرات بحال صنادق بالسمية باش تخبي فيها البيانات. تقدر تحط فيها أرقام ولا كلمات باش تخدم بيهم من بعد!',
    py_obj_1: 'نتعلمو كيفاش نصاوبو متغير|نحطو رقم في المتغير|نطبعو القيمة د المتغير في الكونسول',
    py_tip_1: 'في بايثون ماكتحتاجش تكتب "let" ولا "const" بحال فاللغات الأخرى.',
    py_explain_2: 'الحلقات (Loops) كتعاونك تعاود نفس الكود بلا ما تكتبو بزاف د المرات.',
    py_obj_2: 'نتعلمو حلقة "for"|نفهمو دالة range|نطبعو أرقام متتابعة',
    py_tip_2: 'عقل بلي range(1, 4) كتحبس قبل 4، يعني غتطبع غير 1 و 2 و 3.',
    py_explain_3: 'الشروط هي كيفاش البيسي كيتخذ قرارات. (إذا كان... إذن...).',
    py_obj_3: 'نستعملو شرط "if"|نستعملو "else"|نقارنو الأرقام',
    py_tip_3: 'المسافات في أول السطر مهمة بزاف في بايثون باش الكود يخدم مزيان!',
    py_explain_4: 'الدوال (Functions) هي كود تقدر تعاود تستعملو. كنصاوبوها ب "def".',
    py_obj_4: 'نصاوبو دالة جديدة|نستعملو كلمة "def"|نعيطو للدالة باش تخدم',
    py_tip_4: 'مانساش الأقواس () ملي تعيط لشي دالة.',
    py_explain_5: 'القوائم (Lists) بحال شي تران، كتخليك تجمع بزاف د الحاجات في متغير واحد.',
    py_obj_5: 'نصاوبو قائمة|نفهمو الترتيب من الزيرو|نطبعو العنصر الأول',
    py_tip_5: 'في البرمجة كنبداو الحساب من 0! يعني العنصر الأول هو [0].',
    js_explain_1: 'الكونسول هو أداة للمطورين باش يطبعو الميساجات. كيعاونك تشوف شنو كيدير الكود ديالك في الكواليس.',
    js_obj_1: 'نتعرفو على الكونسول|نتعلمو أمر console.log|نطبعو جملة قاصيرة',
    js_tip_1: 'مانساش دير النص ديالك بين علامات التنصيص \'بحال هكا\'!',
    js_explain_2: 'المتغيرات بحال صنادق للتخزين. في جافاسكريبت كنستعملو "let" باش نصاوبو متغير.',
    js_obj_2: 'نستعملو "let" باش نصاوبو متغير|نعطيو للمتغير قيمة رقمية|نطبعو المتغير',
    js_tip_2: 'مانساش الفاصلة المنقوطة ; في آخر السطر!',
    js_explain_3: 'جملة If/Else كتخلي الكود ديالك يتخذ قرارات على حساب الشروط.',
    js_obj_3: 'نصاوبو بلوك "if"|نصاوبو بلوك "else"|نجربو الشرط',
    js_tip_3: 'استعمل المعقوفات { } باش تجمع الكود ديال if و else.',
    js_explain_4: 'الدوال (Functions) هي كود مصاوب باش يدير مهمة معينة وقتما عيطتي ليه.',
    js_obj_4: 'نصاوبو دالة|نكتبو الكود ديالها|نعيطو ليها باش تخدم',
    js_tip_4: 'الدالة ماكتخدمش حتى تعيط ليها بالأقواس: myFunction()',
    js_explain_5: 'المصفوفات (Arrays) بحال قوائم كتهز بزاف ديال القيم في دقة وحدة.',
    js_obj_5: 'نصاوبو مصفوفة ب []|نزيدو فيها كلمات|نطبعو العنصر الأول',
    js_tip_5: 'المصفوفات كيبداو من 0، يعني العنصر الأول هو [0].',
    bc_challenge_2: 'دور لليسر وزيد القدام.',
    bc_challenge_3: 'تمشى في الطريق!',
    bc_challenge_4: 'خرج من المتاهة!',
    bc_challenge_5: 'اختبار: شنو هي الحلقة (loop)؟',
    bc_challenge_6: 'نقز 5 ديال المرات باستعمال حلقة.',
    bc_challenge_7: 'خدم مع حدث النقر.',
    bc_challenge_8: 'اختبار: شنو هو الحدث (event)؟',
    bc_challenge_9: 'استعمل شرط باش تقلب شي رقم.',
    bc_challenge_10: 'خزن شي قيمة في متغير.',
    bc_challenge_11: 'ولي سيد المنطق!',
    bc_hint_1: 'جرب تكتب console.log("forward") تلاتة ديال المرات!',
    bc_hint_2: 'طبع "left" هي اللولة، ومن بعد "forward".',
    show_hint: 'وريني التلميح',
    hide_hint: 'خبي التلميح',
    py_hint_1: 'المتغيرات بحال الصنادق. استعمل age = 10.',
    py_hint_2: 'استعمل range(1, 4) باش تحصل على الأرقام 1 و 2 و 3.',
    py_hint_3: 'استعمل المسافات (4) قبل الكود ديال "if" و"else".',
    // Python Lesson 1 Quiz (AR)
    py_q1_q1: 'شنو هو المتغير في بايثون؟',
    py_q1_o1a: 'صندوق كيخزن قيمة',
    py_q1_o1b: 'نوع من الحلقات',
    py_q1_o1c: 'دالة كتخدم بوحدها',
    py_q1_o1d: 'كلمة خاصة ببايثون فقط',
    py_q1_f1: 'المتغير هو صندوق باسم كيخزن فيه قيمة، بحال صندوق عليه تيكيت.',
    py_q1_q2: 'أشنو هو الكود الصحيح باش نصاوب متغير "score" ب 10 ؟',
    py_q1_o2a: 'var score = 10',
    py_q1_o2b: 'let score = 10',
    py_q1_o2c: 'score = 10',
    py_q1_o2d: 'int score = 10',
    py_q1_f2: 'في بايثون، كتكتب غير اسم المتغير = القيمة. ماتحتاجش "var" أو "let".',
    py_q1_q3: 'كيفاش كتعرض قيمة متغير في بايثون؟',
    py_q1_o3a: 'display(age)',
    py_q1_o3b: 'print(age)',
    py_q1_o3c: 'console.log(age)',
    py_q1_o3d: 'echo age',
    py_q1_f3: 'في بايثون كنستعملو print() باش نعرضو القيم.',
    // JavaScript Lesson 1 Quiz (AR)
    js_q1_q1: 'شنو كيدير console.log() في جافاسكريبت؟',
    js_q1_o1a: 'كيحفظ البيانات في فايل',
    js_q1_o1b: 'كيطبع رسالة في كونسول المتصفح',
    js_q1_o1c: 'كيعيط alert',
    js_q1_o1d: 'كيتواصل مع سيرفر',
    js_q1_f1: 'console.log() هي الطريقة الأكثر استعمالاً باش تعرض القيم في جافاسكريبت.',
    js_q1_q2: 'أشنو غا تكتب باش تحل كونسول المتصفح؟',
    js_q1_o2a: 'F12',
    js_q1_o2b: 'Ctrl + C',
    js_q1_o2c: 'Alt + F4',
    js_q1_o2d: 'Ctrl + S',
    js_q1_f2: 'F12 كيحل DevTools ديال المتصفح اللي فيه تاب الكونسول.',
    js_q1_q3: 'أشنو كيحيط النص في جافاسكريبت؟',
    js_q1_o3a: 'المعقوفات {}',
    js_q1_o3b: 'القوسان المربعان []',
    js_q1_o3c: 'الأقواس ()',
    js_q1_o3d: 'علامات التنصيص " " أو \' \'',
    js_q1_f3: 'النصوص (strings) لازم تكون بين علامات التنصيص، سواء المزدوجة أو الأحادية.',
    js_hint_1: 'اكتب console.log("Hello, JavaScript!"); بالضبط.',
    js_hint_2: 'استعمل let score = 100; باش تصاوب المتغير ديالك.',
    web_hint_1: 'الوسوم كيبداو بـ < وكيساو بـ >. جرب <h1>Hello World</h1>.',
    web_hint_2: 'استعمل علامات الاقتباس المفردة للسلسلة إلا كان الوسم فيه علامات اقتباس مزدوجة: \'<img src="magic.png">\'.',
    cpp_challenge_1: 'طبع "Hello C++!" في الكونسول.',
    cpp_challenge_2: 'استعمل مؤشر (pointer) باش توصل لشي متغير.',
    cpp_challenge_3: 'اختبار: شنو هي الفئة (class)؟',
    cpp_challenge_4: 'استعمل STL vector.',
    cpp_challenge_5: 'صاوب مكينة حسابية!',
    java_challenge_1: 'طبع "Hello Java" في الكونسول.',
    java_challenge_2: 'صاوب أول فئة (class) جافا ديالك.',
    java_challenge_3: 'اختبار: شنو هي الـ ArrayList؟',
    java_challenge_4: 'صاوب نظام حساب بنكي!',
    sql_challenge_1: 'ختار كاع المستخدمين من قاعدة البيانات.',
    sql_challenge_2: 'عزل المستخدمين على حساب العمر.',
    sql_challenge_3: 'اختبار: شنو هو الـ JOIN؟',
    sql_challenge_4: 'قلب في قاعدة بيانات معقدة!',
    ts_challenge_1: 'عرف شي متغير بنوع محدد.',
    ts_challenge_2: 'صاوب واجهة (interface) للمستخدم.',
    ts_challenge_3: 'اختبار: شنو هي الـ Generics؟',
    ts_challenge_4: 'صاوب ليستة ديال المهام محددة الأنواع!',
    bc_mod_1_title: 'أساسيات المنطق',
    bc_mod_1_desc: 'تعلم البلوكات الأساسية ديال البرمجة.',
    bc_lvl_1_title: 'المستوى 1: التسلسلات',
    bc_lvl_2_title: 'المستوى 2: الحلقات',
    bc_mod_2_title: 'مفاهيم متوسطة',
    bc_mod_2_desc: 'زيد القدام في البرمجة مع الأحداث والبيانات.',
    bc_lvl_3_title: 'المستوى 3: الأحداث',
  },
};

type TranslationKey = keyof (typeof translations)['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
  hasSelectedLanguage: boolean;
  completeLanguageSelection: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return saved ? (saved as Language) : Language.EN;
  });

  const [hasSelectedLanguage, setHasSelectedLanguage] = useState<boolean>(() => {
    return localStorage.getItem('appLanguageSelected') === 'true';
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('appLanguage', newLanguage);
  };

  const completeLanguageSelection = () => {
    setHasSelectedLanguage(true);
    localStorage.setItem('appLanguageSelected', 'true');
  };

  useEffect(() => {
    const dir = language === Language.AR ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language]);

  const t = (key: TranslationKey) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, hasSelectedLanguage, completeLanguageSelection }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
